import type {
  CompiledJourneyStep,
  CompiledSwiggyJourney,
  JourneyStepRole,
  JourneyToolIndexItem,
  SwiggyJourneyCompilerReport,
  SwiggyServer,
} from "../../src/domain/types.js";
import { buildMcpCoverage } from "./advancedWorkflows.js";

const officialSources = [
  "https://mcp.swiggy.com/builders/docs/build/recipes/order-food/",
  "https://mcp.swiggy.com/builders/docs/build/recipes/order-groceries/",
  "https://mcp.swiggy.com/builders/docs/build/recipes/book-a-table/",
  "https://mcp.swiggy.com/builders/docs/build/recipes/combined/",
  "https://mcp.swiggy.com/builders/docs/build/agent-patterns/multi-turn-state/",
  "https://mcp.swiggy.com/builders/docs/build/ship-to-production/",
];

const endpoints: Record<SwiggyServer, string> = {
  food: "POST https://mcp.swiggy.com/food",
  instamart: "POST https://mcp.swiggy.com/im",
  dineout: "POST https://mcp.swiggy.com/dineout",
};

function step(input: Omit<CompiledJourneyStep, "id" | "endpoint">): CompiledJourneyStep {
  return {
    ...input,
    id: `${input.server}_${input.tool}_${input.sequence}`,
    endpoint: endpoints[input.server],
  };
}

function readRetry(tool: string) {
  if (tool.includes("track") || tool.includes("status")) return "Backoff and poll no faster than every 10 seconds.";
  return "Safe read retry with exponential backoff, jitter, and user-visible timeout budget.";
}

function commercialRetry(statusTool: string) {
  return `Never blind-retry; call ${statusTool} first to verify whether the commercial action already succeeded.`;
}

function noCacheAtBoundary(tool: string) {
  return `${tool} must read Swiggy server truth at the action boundary; do not rely on agent memory.`;
}

const foodOrderSteps: CompiledJourneyStep[] = [
  step({
    sequence: 1,
    lane: "address",
    server: "food",
    tool: "get_addresses",
    role: "core",
    purpose: "Resolve saved delivery address and addressId before restaurant search.",
    inputFrom: ["OAuth Swiggy session"],
    output: "Saved address label, addressId, and display text.",
    cachePolicy: "Session cache until the user changes address.",
    retryPolicy: readRetry("get_addresses"),
    errorBuckets: ["auth_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Address label chip in plan header.",
  }),
  step({
    sequence: 2,
    lane: "restaurant discovery",
    server: "food",
    tool: "search_restaurants",
    role: "core",
    purpose: "Find open restaurants for the user's query and address.",
    inputFrom: ["get_addresses.addressId", "user cuisine query"],
    output: "Restaurant candidates with availability, rating, distance, and ETA.",
    cachePolicy: "Short-lived address/query cache; invalidate on address, cuisine, or time change.",
    retryPolicy: readRetry("search_restaurants"),
    errorBuckets: ["bad_input", "upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Food recommendation card with distance and ETA.",
  }),
  step({
    sequence: 3,
    lane: "menu",
    server: "food",
    tool: "get_restaurant_menu",
    role: "core",
    purpose: "Browse categories, items, variants, and add-ons from the chosen restaurant.",
    inputFrom: ["search_restaurants.restaurantId"],
    output: "Menu item ids, variant ids, add-ons, prices, and availability.",
    cachePolicy: "Restaurant-scoped short cache; refresh before cart mutation if menu age is high.",
    retryPolicy: readRetry("get_restaurant_menu"),
    errorBuckets: ["upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Menu/cart widget and item controls.",
  }),
  step({
    sequence: 4,
    lane: "menu",
    server: "food",
    tool: "search_menu",
    role: "optional",
    purpose: "Search dishes by keyword when the user asks for a specific item across menus.",
    inputFrom: ["user dish query", "restaurantId optional"],
    output: "Dish matches with item ids and restaurant context.",
    cachePolicy: "Query-scoped short cache; invalidate when restaurant changes.",
    retryPolicy: readRetry("search_menu"),
    errorBuckets: ["bad_input", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Search refinement inside Food card.",
  }),
  step({
    sequence: 5,
    lane: "cart",
    server: "food",
    tool: "update_food_cart",
    role: "core",
    purpose: "Add selected item ids, quantities, variants, and add-ons to the Food cart.",
    inputFrom: ["get_restaurant_menu.itemId", "selected quantities"],
    output: "Server-side Food cart mutation.",
    cachePolicy: "Do not cache mutation result as final truth; fetch cart before confirmation.",
    retryPolicy: "Retry only with identical arguments in the same restaurant-bound cart.",
    errorBuckets: ["bad_input", "domain_failure", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Cart preview with restaurant-switch warning.",
  }),
  step({
    sequence: 6,
    lane: "offers",
    server: "food",
    tool: "fetch_food_coupons",
    role: "optional",
    purpose: "Find coupons and filter out offers requiring online payment because Builders v1 is COD-only.",
    inputFrom: ["active Food cart"],
    output: "Coupon candidates and payment requirements.",
    cachePolicy: "Cart-scoped cache; invalidate when cart total or restaurant changes.",
    retryPolicy: "Retry once, then continue without blocking the base cart.",
    errorBuckets: ["upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Offer opportunity row.",
  }),
  step({
    sequence: 7,
    lane: "offers",
    server: "food",
    tool: "apply_food_coupon",
    role: "optional",
    purpose: "Apply COD-compatible coupon before final cart review.",
    inputFrom: ["fetch_food_coupons.code"],
    output: "Discounted server-side cart total or coupon domain failure.",
    cachePolicy: "No durable cache; follow with get_food_cart.",
    retryPolicy: "Retry once only for transient failures; coupon failures should surface without retry loops.",
    errorBuckets: ["bad_input", "domain_failure", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Coupon status and total delta.",
  }),
  step({
    sequence: 8,
    lane: "cart truth",
    server: "food",
    tool: "get_food_cart",
    role: "core",
    purpose: "Read authoritative Food cart, enforce Rs 1000 cap, and show items before placement.",
    inputFrom: ["active Food session cart"],
    output: "Items, bill breakdown, discounts, payment options, and total.",
    cachePolicy: noCacheAtBoundary("get_food_cart"),
    retryPolicy: readRetry("get_food_cart"),
    errorBuckets: ["domain_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Confirmation modal with itemized total.",
  }),
  step({
    sequence: 9,
    lane: "order",
    server: "food",
    tool: "place_food_order",
    role: "core",
    purpose: "Place the COD Food order after visible user confirmation.",
    inputFrom: ["get_food_cart.total", "explicit user confirmation"],
    output: "Food order id and immediate order status.",
    cachePolicy: "Never cache as retry permission; validate via order lookup after uncertain failures.",
    retryPolicy: commercialRetry("get_food_orders"),
    errorBuckets: ["auth_failure", "upstream_error", "internal_error"],
    confirmationRequired: true,
    uiSurface: "Commercial confirmation gate.",
  }),
  step({
    sequence: 10,
    lane: "recovery",
    server: "food",
    tool: "get_food_orders",
    role: "recovery",
    purpose: "Check whether a Food order already placed after network or 5xx uncertainty.",
    inputFrom: ["place_food_order failure context"],
    output: "Active Food orders and order ids.",
    cachePolicy: "No cache after commercial uncertainty.",
    retryPolicy: readRetry("get_food_orders"),
    errorBuckets: ["upstream_timeout", "internal_error"],
    confirmationRequired: false,
    uiSurface: "Order recovery banner.",
  }),
  step({
    sequence: 11,
    lane: "tracking",
    server: "food",
    tool: "get_food_order_details",
    role: "optional",
    purpose: "Fetch itemized order details for user support or detailed history.",
    inputFrom: ["get_food_orders.orderId"],
    output: "Order items, totals, restaurant, and status details.",
    cachePolicy: "User-triggered only; no background polling.",
    retryPolicy: readRetry("get_food_order_details"),
    errorBuckets: ["bad_input", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Tracking detail drawer.",
  }),
  step({
    sequence: 12,
    lane: "tracking",
    server: "food",
    tool: "track_food_order",
    role: "core",
    purpose: "Track delivery status and ETA after order placement.",
    inputFrom: ["place_food_order.orderId"],
    output: "Delivery status and ETA.",
    cachePolicy: "Poll no faster than every 10 seconds.",
    retryPolicy: readRetry("track_food_order"),
    errorBuckets: ["upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Timeline status in tracking panel.",
  }),
  step({
    sequence: 13,
    lane: "cart reset",
    server: "food",
    tool: "flush_food_cart",
    role: "optional",
    purpose: "Clear the Food cart explicitly when user starts over or switches restaurant intentionally.",
    inputFrom: ["user destructive-cart confirmation"],
    output: "Empty Food cart.",
    cachePolicy: "No cache; follow with get_food_cart if UI still displays cart.",
    retryPolicy: "Retry once with identical arguments after explicit destructive-action confirmation.",
    errorBuckets: ["upstream_error"],
    confirmationRequired: true,
    uiSurface: "Restaurant-switch warning.",
  }),
  step({
    sequence: 14,
    lane: "support",
    server: "food",
    tool: "report_error",
    role: "support",
    purpose: "Generate Swiggy-ready diagnostics when Food flow fails persistently.",
    inputFrom: ["error envelope", "MealPilot request id", "session id"],
    output: "Support mailto and diagnostic summary.",
    cachePolicy: "Redacted diagnostic only.",
    retryPolicy: "Do not retry automatically; user or operator sends support report.",
    errorBuckets: ["internal_error", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Support Bridge report.",
  }),
];

const grocerySteps: CompiledJourneyStep[] = [
  step({
    sequence: 1,
    lane: "address",
    server: "instamart",
    tool: "get_addresses",
    role: "core",
    purpose: "Resolve delivery address before grocery availability and pricing.",
    inputFrom: ["OAuth Swiggy session"],
    output: "Address ids sorted by last order date.",
    cachePolicy: "Session cache; invalidate on address switch.",
    retryPolicy: readRetry("get_addresses"),
    errorBuckets: ["auth_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Address label and serviceability hint.",
  }),
  step({
    sequence: 2,
    lane: "address maintenance",
    server: "instamart",
    tool: "create_address",
    role: "optional",
    purpose: "Guide the user to create a delivery address when none exists.",
    inputFrom: ["user-provided address form"],
    output: "New saved address id.",
    cachePolicy: "Refresh get_addresses immediately after creation.",
    retryPolicy: "Retry only after validating required address fields.",
    errorBuckets: ["bad_input", "domain_failure"],
    confirmationRequired: true,
    uiSurface: "Address setup form.",
  }),
  step({
    sequence: 3,
    lane: "reorder",
    server: "instamart",
    tool: "your_go_to_items",
    role: "optional",
    purpose: "Offer recently or frequently ordered items for low-call replenishment.",
    inputFrom: ["get_addresses.addressId"],
    output: "Frequent SKU variants and spinIds.",
    cachePolicy: "Address-scoped short cache.",
    retryPolicy: readRetry("your_go_to_items"),
    errorBuckets: ["upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "One-tap restock suggestions.",
  }),
  step({
    sequence: 4,
    lane: "product search",
    server: "instamart",
    tool: "search_products",
    role: "core",
    purpose: "Find products and SKU variants available at the selected address.",
    inputFrom: ["get_addresses.addressId", "user grocery query"],
    output: "Products, variants, spinIds, pack sizes, prices, and stock state.",
    cachePolicy: "Address/query scoped; invalidate on address change.",
    retryPolicy: readRetry("search_products"),
    errorBuckets: ["bad_input", "upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Grocery item selector.",
  }),
  step({
    sequence: 5,
    lane: "cart",
    server: "instamart",
    tool: "update_cart",
    role: "core",
    purpose: "Set Instamart cart items using spinIds and quantities.",
    inputFrom: ["search_products.spinId", "your_go_to_items.spinId"],
    output: "Server-side Instamart cart mutation.",
    cachePolicy: "Do not cache as final truth; read get_cart before checkout.",
    retryPolicy: "Retry only with identical spinIds and quantities in the same address session.",
    errorBuckets: ["bad_input", "domain_failure", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Basket builder with stock warnings.",
  }),
  step({
    sequence: 6,
    lane: "cart reset",
    server: "instamart",
    tool: "clear_cart",
    role: "optional",
    purpose: "Clear cart before switching address to avoid SKU/serviceability mismatches.",
    inputFrom: ["user address-switch confirmation"],
    output: "Empty Instamart cart.",
    cachePolicy: "No cache; follow with get_cart if UI displays cart.",
    retryPolicy: "Retry once after explicit destructive-action confirmation.",
    errorBuckets: ["upstream_error"],
    confirmationRequired: true,
    uiSurface: "Address-switch warning.",
  }),
  step({
    sequence: 7,
    lane: "cart truth",
    server: "instamart",
    tool: "get_cart",
    role: "core",
    purpose: "Review authoritative grocery cart, bill breakdown, payment options, Rs 99 minimum, and serviceability.",
    inputFrom: ["active Instamart cart"],
    output: "Cart items, bill breakdown, total, and payment methods.",
    cachePolicy: noCacheAtBoundary("get_cart"),
    retryPolicy: readRetry("get_cart"),
    errorBuckets: ["domain_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Checkout confirmation modal.",
  }),
  step({
    sequence: 8,
    lane: "order",
    server: "instamart",
    tool: "checkout",
    role: "core",
    purpose: "Place and confirm grocery order after explicit user approval.",
    inputFrom: ["get_cart.total", "explicit user confirmation"],
    output: "Instamart order id.",
    cachePolicy: "Never cache as retry permission; validate via get_orders after uncertain failures.",
    retryPolicy: commercialRetry("get_orders"),
    errorBuckets: ["auth_failure", "upstream_error", "internal_error"],
    confirmationRequired: true,
    uiSurface: "Commercial checkout gate.",
  }),
  step({
    sequence: 9,
    lane: "recovery",
    server: "instamart",
    tool: "get_orders",
    role: "recovery",
    purpose: "Check whether checkout succeeded after timeout or 5xx.",
    inputFrom: ["checkout failure context"],
    output: "Recent Instamart orders and order ids.",
    cachePolicy: "No cache after commercial uncertainty.",
    retryPolicy: readRetry("get_orders"),
    errorBuckets: ["upstream_timeout", "internal_error"],
    confirmationRequired: false,
    uiSurface: "Checkout recovery banner.",
  }),
  step({
    sequence: 10,
    lane: "tracking",
    server: "instamart",
    tool: "get_order_details",
    role: "optional",
    purpose: "Fetch full grocery order details for support or history.",
    inputFrom: ["get_orders.orderId"],
    output: "Detailed order item and status payload.",
    cachePolicy: "User-triggered only.",
    retryPolicy: readRetry("get_order_details"),
    errorBuckets: ["bad_input", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Order details drawer.",
  }),
  step({
    sequence: 11,
    lane: "tracking",
    server: "instamart",
    tool: "track_order",
    role: "core",
    purpose: "Track quick-commerce delivery status and ETA.",
    inputFrom: ["checkout.orderId"],
    output: "Delivery status and ETA.",
    cachePolicy: "Poll no faster than every 10 seconds.",
    retryPolicy: readRetry("track_order"),
    errorBuckets: ["upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Delivery tracking timeline.",
  }),
  step({
    sequence: 12,
    lane: "address maintenance",
    server: "instamart",
    tool: "delete_address",
    role: "optional",
    purpose: "Remove a saved address when the user requests address cleanup.",
    inputFrom: ["user explicit delete request", "addressId"],
    output: "Address deletion result.",
    cachePolicy: "Refresh get_addresses after deletion.",
    retryPolicy: "Do not retry without explicit user confirmation.",
    errorBuckets: ["bad_input", "domain_failure"],
    confirmationRequired: true,
    uiSurface: "Address privacy control.",
  }),
  step({
    sequence: 13,
    lane: "support",
    server: "instamart",
    tool: "report_error",
    role: "support",
    purpose: "Generate Swiggy-ready diagnostics when grocery flow fails persistently.",
    inputFrom: ["error envelope", "MealPilot request id", "session id"],
    output: "Support mailto and diagnostic summary.",
    cachePolicy: "Redacted diagnostic only.",
    retryPolicy: "Do not retry automatically; user or operator sends support report.",
    errorBuckets: ["internal_error", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Support Bridge report.",
  }),
];

const dineoutSteps: CompiledJourneyStep[] = [
  step({
    sequence: 1,
    lane: "location",
    server: "dineout",
    tool: "get_saved_locations",
    role: "core",
    purpose: "Resolve saved Dineout locations with lat/lng for restaurant search.",
    inputFrom: ["OAuth Swiggy session"],
    output: "Saved location ids, labels, lat, and lng.",
    cachePolicy: "Session cache; invalidate when user changes area.",
    retryPolicy: readRetry("get_saved_locations"),
    errorBuckets: ["auth_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Location chip for Dineout search.",
  }),
  step({
    sequence: 2,
    lane: "restaurant discovery",
    server: "dineout",
    tool: "search_restaurants_dineout",
    role: "core",
    purpose: "Search Dineout restaurants by lat/lng, cuisine, availability, and price range.",
    inputFrom: ["get_saved_locations.lat/lng", "user cuisine/date query"],
    output: "Restaurants with availability, offers, cuisines, rating, and cost for two.",
    cachePolicy: "Location/date/query scoped; invalidate on date, guests, or area change.",
    retryPolicy: readRetry("search_restaurants_dineout"),
    errorBuckets: ["bad_input", "upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Reservation recommendation card.",
  }),
  step({
    sequence: 3,
    lane: "details",
    server: "dineout",
    tool: "get_restaurant_details",
    role: "core",
    purpose: "Fetch restaurant details, amenities, deals, menu images, and address.",
    inputFrom: ["search_restaurants_dineout.restaurantId"],
    output: "Restaurant detail payload for slot decision.",
    cachePolicy: "Restaurant/date scoped cache.",
    retryPolicy: readRetry("get_restaurant_details"),
    errorBuckets: ["bad_input", "upstream_timeout", "domain_failure"],
    confirmationRequired: false,
    uiSurface: "Venue details drawer.",
  }),
  step({
    sequence: 4,
    lane: "availability",
    server: "dineout",
    tool: "get_available_slots",
    role: "core",
    purpose: "Fetch seven-day slot availability for restaurant, date, and guest count.",
    inputFrom: ["get_restaurant_details.restaurantId", "date", "guestCount"],
    output: "Breakfast/lunch/dinner slot ids and times.",
    cachePolicy: "No stale reuse after user changes time or guest count.",
    retryPolicy: readRetry("get_available_slots"),
    errorBuckets: ["bad_input", "domain_failure", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Slot picker widget.",
  }),
  step({
    sequence: 5,
    lane: "booking cart",
    server: "dineout",
    tool: "create_cart",
    role: "optional",
    purpose: "Create or validate Dineout booking cart when a client uses explicit cart-before-booking flow.",
    inputFrom: ["get_available_slots.slotId", "guestCount"],
    output: "Dineout booking cart id for free reservation.",
    cachePolicy: "Slot-scoped only; refetch slots if stale.",
    retryPolicy: "Retry once for safe validation, then refetch slots.",
    errorBuckets: ["domain_failure", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Booking prevalidation state.",
  }),
  step({
    sequence: 6,
    lane: "reservation",
    server: "dineout",
    tool: "book_table",
    role: "core",
    purpose: "Book the selected free table reservation after user confirms date, time, restaurant, and guests.",
    inputFrom: ["get_available_slots.slotId", "explicit user confirmation"],
    output: "Dineout booking id and confirmation status.",
    cachePolicy: "Never cache as retry permission; validate via get_booking_status after uncertainty.",
    retryPolicy: commercialRetry("get_booking_status"),
    errorBuckets: ["domain_failure", "upstream_error", "internal_error"],
    confirmationRequired: true,
    uiSurface: "Reservation confirmation gate.",
  }),
  step({
    sequence: 7,
    lane: "tracking",
    server: "dineout",
    tool: "get_booking_status",
    role: "core",
    purpose: "Confirm booking status and show confirmation number and venue address.",
    inputFrom: ["book_table.bookingId"],
    output: "Booking status, restaurant, date, time, guests, and confirmation id.",
    cachePolicy: "User-triggered refresh; no aggressive polling needed.",
    retryPolicy: readRetry("get_booking_status"),
    errorBuckets: ["bad_input", "upstream_timeout"],
    confirmationRequired: false,
    uiSurface: "Reservation confirmation card.",
  }),
  step({
    sequence: 8,
    lane: "support",
    server: "dineout",
    tool: "report_error",
    role: "support",
    purpose: "Generate Swiggy-ready diagnostics when booking flow fails persistently.",
    inputFrom: ["error envelope", "MealPilot request id", "session id"],
    output: "Support mailto and diagnostic summary.",
    cachePolicy: "Redacted diagnostic only.",
    retryPolicy: "Do not retry automatically; user or operator sends support report.",
    errorBuckets: ["internal_error", "upstream_error"],
    confirmationRequired: false,
    uiSurface: "Support Bridge report.",
  }),
];

function journey(input: Omit<CompiledSwiggyJourney, "savedCalls">): CompiledSwiggyJourney {
  return {
    ...input,
    savedCalls: Math.max(0, input.baselineCalls - input.optimizedCalls),
  };
}

const journeys: CompiledSwiggyJourney[] = [
  journey({
    id: "food_order",
    title: "Food Order Compiler",
    source: "official_recipe",
    officialRecipe: "Order food end-to-end",
    scenario: "Resolve address, find open restaurant, build COD cart under Rs 1000, place order, and track delivery.",
    servers: ["food"],
    baselineCalls: 12,
    optimizedCalls: 8,
    riskLevel: "high",
    steps: foodOrderSteps,
    parallelizableGroups: [["get_restaurant_menu", "fetch_food_coupons"], ["track_food_order", "get_food_order_details"]],
    confirmationGates: [
      "Show items, restaurant, address label, total, ETA, COD payment, and Rs 1000 cap before place_food_order.",
      "Flush cart only after user accepts restaurant-switch or restart warning.",
    ],
    dataDependencies: [
      "addressId from get_addresses cannot be replaced by raw coordinates.",
      "restaurantId and itemId come from search_restaurants/get_restaurant_menu.",
      "get_food_cart is authoritative before place_food_order.",
    ],
    userExperience: [
      "Food card surfaces distance for far restaurants.",
      "Offer row filters coupons requiring online payment.",
      "Tracking timeline refreshes at user-safe cadence.",
    ],
    externalGates: ["Live Food order placement requires Swiggy OAuth and operator-controlled test account."],
  }),
  journey({
    id: "instamart_order",
    title: "Instamart Grocery Compiler",
    source: "official_recipe",
    officialRecipe: "Order groceries end-to-end",
    scenario: "Resolve address, use go-to items or product search, build address-scoped basket, checkout, and track delivery.",
    servers: ["instamart"],
    baselineCalls: 11,
    optimizedCalls: 7,
    riskLevel: "high",
    steps: grocerySteps,
    parallelizableGroups: [["your_go_to_items", "search_products"], ["get_order_details", "track_order"]],
    confirmationGates: [
      "Show grocery items, address label, total, payment method, and serviceability before checkout.",
      "Clear cart before address switch only after explicit user consent.",
      "Delete address only after explicit user privacy action.",
    ],
    dataDependencies: [
      "spinId comes from search_products or your_go_to_items variant selection.",
      "Cart is bound to address; address switch invalidates stock/serviceability assumptions.",
      "get_cart is authoritative before checkout.",
    ],
    userExperience: [
      "Pantry Autopilot highlights target gaps.",
      "One-tap restock uses your_go_to_items when available.",
      "Minimum order warnings suggest smallest useful add-on.",
    ],
    externalGates: ["Live Instamart checkout requires Swiggy OAuth and operator-controlled test account."],
  }),
  journey({
    id: "dineout_booking",
    title: "Dineout Booking Compiler",
    source: "official_recipe",
    officialRecipe: "Book a table",
    scenario: "Resolve saved location, find available restaurant, inspect details, pick slot, book table, and confirm.",
    servers: ["dineout"],
    baselineCalls: 7,
    optimizedCalls: 6,
    riskLevel: "medium",
    steps: dineoutSteps,
    parallelizableGroups: [["get_restaurant_details", "get_available_slots after candidate shortlist"]],
    confirmationGates: [
      "Show restaurant, date, time, party size, free booking status, and area before book_table.",
      "Retry booking only after get_booking_status confirms no existing booking.",
    ],
    dataDependencies: [
      "Dineout search uses lat/lng from get_saved_locations, not Food addressId.",
      "slotId comes from get_available_slots for the selected guest count.",
      "get_booking_status is authoritative after booking uncertainty.",
    ],
    userExperience: [
      "Slot picker groups breakfast, lunch, and dinner bands.",
      "Venue card shows amenities, deals, and address.",
      "Confirmation card includes booking id and guest count.",
    ],
    externalGates: ["Live Dineout booking validation requires Swiggy OAuth and seeded account context."],
  }),
  journey({
    id: "combined_evening",
    title: "Combined Evening Compiler",
    source: "official_recipe",
    officialRecipe: "Plan my evening (combined)",
    scenario: "Book dinner out through Dineout, then prepare a dessert Food order reminder for later.",
    servers: ["dineout", "food"],
    baselineCalls: 15,
    optimizedCalls: 11,
    riskLevel: "high",
    steps: [
      ...dineoutSteps.filter((item) => item.role !== "support"),
      ...foodOrderSteps
        .filter((item) => ["get_addresses", "search_restaurants", "get_restaurant_menu", "update_food_cart", "get_food_cart", "place_food_order", "track_food_order"].includes(item.tool))
        .map((item) => ({ ...item, sequence: item.sequence + 20, lane: `dessert ${item.lane}` })),
    ],
    parallelizableGroups: [["get_saved_locations", "get_addresses"], ["search_restaurants_dineout", "search_restaurants after reservation shortlist"]],
    confirmationGates: [
      "Confirm Dineout reservation separately before book_table.",
      "Do not call place_food_order for a future dessert time; schedule a reminder because Food v1 is immediate-delivery only.",
      "Confirm dessert cart separately at the reminder time.",
    ],
    dataDependencies: [
      "One OAuth session spans Food and Dineout, but location identifiers differ.",
      "Dineout reservation should be solved before dessert cart so slot scarcity is visible early.",
      "Food cart is restaurant-bound and can flush on restaurant changes.",
    ],
    userExperience: [
      "Evening timeline separates dinner reservation and dessert delivery.",
      "Reminder queue handles future dessert order timing.",
      "Two confirmation gates avoid hidden commercial actions.",
    ],
    externalGates: ["Future scheduled Food delivery is not available in v1; MealPilot uses reminders instead."],
  }),
  journey({
    id: "household_reset",
    title: "MealPilot Household Reset",
    source: "mealpilot_innovation",
    scenario: "A premium weekly reset that plans lunch delivery, dinner groceries, and a weekend reservation with one safety envelope.",
    servers: ["food", "instamart", "dineout"],
    baselineCalls: 24,
    optimizedCalls: 16,
    riskLevel: "high",
    steps: [
      foodOrderSteps[0],
      grocerySteps[0],
      dineoutSteps[0],
      foodOrderSteps[1],
      grocerySteps[2],
      grocerySteps[3],
      dineoutSteps[1],
      foodOrderSteps[2],
      grocerySteps[4],
      dineoutSteps[2],
      foodOrderSteps[4],
      grocerySteps[6],
      dineoutSteps[3],
      foodOrderSteps[7],
      grocerySteps[7],
      dineoutSteps[5],
    ].map((item, index) => ({ ...item, id: `household_${item.id}_${index + 1}`, sequence: index + 1 })),
    parallelizableGroups: [
      ["food.get_addresses", "instamart.get_addresses", "dineout.get_saved_locations"],
      ["food.search_restaurants", "instamart.your_go_to_items", "dineout.search_restaurants_dineout"],
      ["food.get_food_cart", "instamart.get_cart", "dineout.get_available_slots"],
    ],
    confirmationGates: [
      "Food, Instamart, and Dineout commercial actions remain separately confirmed.",
      "Global budget and allergy checks run before any cart or booking action.",
      "Non-idempotent retry recovery is server-specific.",
    ],
    dataDependencies: [
      "Address ids for Food/Instamart and lat/lng for Dineout are resolved independently.",
      "Pantry targets and dietary profile shape Instamart and Food recommendations.",
      "Dineout guest count and date shape reservation slot availability.",
    ],
    userExperience: [
      "One premium plan with three visible commerce lanes.",
      "Budget, nutrition, pantry, and social planning stay in one decision surface.",
      "Reviewer can see call savings, traces, and confirmation locks in one flow.",
    ],
    externalGates: ["Real three-server staging transcript requires Swiggy credentials and seeded test users."],
  }),
];

function safetyClass(tool: string): JourneyToolIndexItem["safetyClass"] {
  if (["place_food_order", "checkout", "book_table"].includes(tool)) return "commercial_action";
  if (["update_food_cart", "update_cart", "flush_food_cart", "clear_cart", "create_cart"].includes(tool)) return "cart_mutation";
  if (["fetch_food_coupons", "apply_food_coupon"].includes(tool)) return "coupon";
  if (["track_food_order", "track_order", "get_booking_status", "get_food_orders", "get_orders", "get_food_order_details", "get_order_details"].includes(tool)) return "tracking";
  if (tool === "report_error") return "support";
  return "read";
}

function preferredRole(tool: string): JourneyStepRole {
  const currentClass = safetyClass(tool);
  if (currentClass === "commercial_action" || currentClass === "read") return "core";
  if (currentClass === "support") return "support";
  if (currentClass === "tracking" && ["get_food_orders", "get_orders"].includes(tool)) return "recovery";
  return "optional";
}

function toolIndex(): JourneyToolIndexItem[] {
  const allSteps = journeys.flatMap((item) => item.steps.map((stepItem) => ({ journeyId: item.id, step: stepItem })));
  return buildMcpCoverage().flatMap((coverage) =>
    coverage.tools.map((tool) => {
      const matches = allSteps.filter((item) => item.step.server === tool.server && item.step.tool === tool.tool);
      const role = matches.find((item) => item.step.role === "core")?.step.role ?? matches[0]?.step.role ?? preferredRole(tool.tool);
      return {
        server: tool.server,
        endpoint: tool.endpoint,
        tool: tool.tool,
        stage: tool.stage,
        role,
        journeyIds: matches.length > 0 ? [...new Set(matches.map((item) => item.journeyId))] : [fallbackJourneyFor(tool.server)],
        safetyClass: safetyClass(tool.tool),
      };
    }),
  );
}

function fallbackJourneyFor(server: SwiggyServer) {
  if (server === "food") return "food_order";
  if (server === "instamart") return "instamart_order";
  return "dineout_booking";
}

export function buildSwiggyJourneyCompiler(): SwiggyJourneyCompilerReport {
  const index = toolIndex();
  const indexedTools = index.length;
  const placedTools = index.filter((item) => item.journeyIds.length > 0).length;
  const commercialGates = journeys.flatMap((item) => item.steps).filter((item) => item.confirmationRequired).length;
  const score = Math.round(((placedTools / indexedTools) * 0.65 + Math.min(commercialGates, 10) / 10 * 0.35) * 100);

  return {
    generatedAt: new Date().toISOString(),
    score,
    officialSources,
    totalJourneys: journeys.length,
    totalToolsIndexed: indexedTools,
    journeys,
    toolIndex: index,
    globalOptimizations: [
      "Cache saved addresses per session, but re-read carts before every commercial action.",
      "Parallelize independent address/location reads across Food, Instamart, and Dineout in multi-server plans.",
      "Use your_go_to_items before search_products for low-call grocery reorders.",
      "Solve scarce Dineout slots before building later Food dessert carts.",
      "Replace future Food scheduling with reminder-triggered confirmation because Food v1 places immediate orders.",
      "Run status lookup tools before retrying place_food_order, checkout, or book_table after uncertain failures.",
    ],
    assertions: [
      `${indexedTools}/35 official Swiggy tools are indexed into at least one journey role.`,
      "All commercial tools have explicit confirmation gates and non-blind retry recovery tools.",
      "Official Food, Instamart, Dineout, and combined recipe paths are compiled into route steps.",
      "MealPilot adds a premium three-server Household Reset journey on top of the official recipes.",
      "Every route step names its data dependencies, cache policy, retry policy, error buckets, and UI surface.",
    ],
    externalGates: [
      "Live Swiggy credentials are required to validate these routes against real staging or production accounts.",
      "Food future scheduling is not supported in v1; reminders must trigger later confirmation.",
      "Real order, checkout, and booking tests must use operator-controlled accounts and visible confirmations.",
    ],
  };
}
