import type { ServerConfig } from "../config.js";
import type { LaunchBundle, LaunchBundleArtifact, LaunchBundlePhase, MealPlan, SwiggyServer } from "../../src/domain/types.js";

const requestedServers: SwiggyServer[] = ["food", "instamart", "dineout"];

function hasClientId(config: ServerConfig) {
  return config.swiggyClientId !== "replace_after_builder_access";
}

function statusScore(status: "ready" | "manual_input" | "external_gate") {
  if (status === "ready") return 1;
  if (status === "manual_input") return 0.65;
  return 0.35;
}

function buildArtifacts(latestPlan?: MealPlan): LaunchBundleArtifact[] {
  return [
    {
      id: "website_atlas",
      label: "Swiggy Website Atlas",
      path: "/api/swiggy-website-atlas",
      category: "api",
      status: "ready",
      evidence: "Maps Builders header, docs subnav, footer, page modules, CTAs, and legal/resource links.",
    },
    {
      id: "module_intelligence",
      label: "Swiggy Builders Module Intelligence Center",
      path: "/api/swiggy-builders-module-intelligence",
      category: "api",
      status: "ready",
      evidence:
        "Turns every Builders website module into owner, audience, product promise, route optimization, risk boundary, proof links, and module journeys.",
    },
    {
      id: "journey_gates",
      label: "Swiggy Builders Journey Gate Center",
      path: "/api/swiggy-builders-journey-gates",
      category: "api",
      status: "ready",
      evidence:
        "Maps the official five-step Builders path into owner-assigned gates, criteria, proof links, telemetry, blockers, and external Swiggy approvals.",
    },
    {
      id: "homepage_experience",
      label: "Swiggy Builders Homepage Experience Center",
      path: "/api/swiggy-builders-homepage-experience",
      category: "api",
      status: "ready",
      evidence:
        "Maps header, hero, how-it-works, benefits, guidelines, FAQ, final CTA, and footer sections into proof, mobile checks, reviewer checks, and external gates.",
    },
    {
      id: "source_evolution",
      label: "Swiggy Builders Source Evolution Center",
      path: "/api/swiggy-builders-source-evolution",
      category: "api",
      status: "ready",
      evidence:
        "Reconciles homepage 18+ launch copy with current 35/35 callable-tool coverage, upstream roadmap drift, docs refresh loops, source gates, and reviewer packet regression.",
    },
    {
      id: "live_source_resilience",
      label: "Swiggy Builders Live Source Resilience Center",
      path: "/api/swiggy-builders-live-source-resilience",
      category: "api",
      status: "ready",
      evidence:
        "Reports live Builders homepage fetch mode, Website Atlas fallback, page mesh coverage, llms markdown recovery, header/footer/CTA parity, and re-browse gates.",
    },
    {
      id: "builders_launch_story",
      label: "Swiggy Builders Launch Story Center",
      path: "/api/swiggy-builders-launch-story",
      category: "api",
      status: "ready",
      evidence:
        "Curates the Builders Club launch-blog narrative into a reviewer demo story, current 35-tool reconciliation, showcase assets, CTA paths, and co-marketing gates.",
    },
    {
      id: "operating_contract_center",
      label: "Swiggy Operating Contract Center",
      path: "/api/swiggy-operating-contract-center",
      category: "api",
      status: "ready",
      evidence:
        "Consolidates official SLA, rate-limit, support, versioning, changelog, and ship-to-production guidance into one reviewer operating contract with runbooks and external gates.",
    },
    {
      id: "deep_site_map",
      label: "Swiggy Deep Site Map",
      path: "/api/swiggy-deep-site-map",
      category: "api",
      status: "ready",
      evidence:
        "Consolidates every Builders page, module signal, CTA, header/docs/footer link, proof path, source section, assertion, and external gate into one reviewer audit.",
    },
    {
      id: "developer_quickstart",
      label: "Developer Quickstart Workbench",
      path: "/api/swiggy-developer-quickstart",
      category: "api",
      status: "ready",
      evidence:
        "Turns Swiggy's self-serve developer quickstart into readiness steps, framework adapters, first-call JSON-RPC drills, auth gates, and recipe handoffs.",
    },
    {
      id: "cta_execution",
      label: "CTA Execution Center",
      path: "/api/swiggy-cta-execution-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns every official Builders CTA, global header link, docs nav link, footer resource, mailto, form, and legal link into a click-ready action matrix with proof links and manual gates.",
    },
    {
      id: "builder_intake",
      label: "Builder Intake Command Center",
      path: "/api/swiggy-builder-intake",
      category: "api",
      status: "ready",
      evidence:
        "Turns every signup, apply, demo, contact, docs, and footer CTA into an owner, next action, evidence link, form field, storyboard, and draft handoff.",
    },
    {
      id: "faq_policy",
      label: "FAQ & Policy Center",
      path: "/api/swiggy-faq-policy",
      category: "api",
      status: "ready",
      evidence:
        "Maps homepage, developer, enterprise, access-ground-rule, footer-resource, allowed, restricted, prohibited, operating-principle, and legal FAQ/policy signals to MealPilot proof.",
    },
    {
      id: "faq_resolution",
      label: "Swiggy FAQ Resolution Center",
      path: "/api/swiggy-faq-resolution-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns public Builders FAQ questions and policy rules into reviewer-ready answers, CTAs, proof routes, owners, and external gates.",
    },
    {
      id: "growth_partnership",
      label: "Growth Partnership Center",
      path: "/api/swiggy-growth-partnership",
      category: "api",
      status: "ready",
      evidence:
        "Turns Swiggy's get-noticed, co-branding, direct-support, hiring, co-marketing, analytics, and growth-partnership promises into experiments, assets, metrics, and external partner asks.",
    },
    {
      id: "talent_signal",
      label: "Swiggy Builder Talent Signal Center",
      path: "/api/swiggy-talent-signal-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns Swiggy's standout-project, demo, GitHub, and hiring-visibility signals into portfolio assets, talent paths, outreach copy, proof routes, and Swiggy-owned gates.",
    },
    {
      id: "conversion_center",
      label: "Swiggy Builders Conversion Center",
      path: "/api/swiggy-conversion-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns the final What Will You Cook CTA module, Start Building, Request Access, Send Demo, builders@swiggy.in, llms.txt, and llms-full.txt into one operator handoff funnel.",
    },
    {
      id: "benefits_activation",
      label: "Swiggy Benefits Activation Center",
      path: "/api/swiggy-benefits-activation-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns Builders benefits into owner-assigned activation lanes for live APIs, quotas, support, co-branding, visibility, growth, hiring, and enterprise gates.",
    },
    {
      id: "channel_multimodal_studio",
      label: "Channel & Multimodal Studio",
      path: "/api/channel-multimodal-studio",
      category: "api",
      status: "ready",
      evidence:
        "Turns Swiggy's developer-page ideas into voice, web chat, Slack/Teams, mobile camera, enterprise, and screenshot-to-order contracts with MCP toolchains and gates.",
    },
    {
      id: "visual_dish_capture",
      label: "Swiggy Visual Dish Capture Center",
      path: "/api/swiggy-visual-dish-capture",
      category: "api",
      status: "ready",
      evidence:
        "Productizes screenshot-to-order with Food menu matches, Instamart ingredient rescue, Dineout place discovery, sample capture analysis, privacy guardrails, and confirmation gates.",
    },
    {
      id: "voice_commerce_center",
      label: "Swiggy Voice Commerce Rehearsal Center",
      path: "/api/swiggy-voice-commerce-center",
      category: "api",
      status: "ready",
      evidence:
        "Productizes voice-vs-chat guidance with short TTS scripts, card fallbacks, no raw ids, no raw-audio retention, confirmation readbacks, and Swiggy route rehearsal.",
    },
    {
      id: "quality_loop_center",
      label: "Swiggy Quality Loop Center",
      path: "/api/swiggy-quality-loop-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns post-order, grocery, booking, and combined feedback into consented learning tags, support-safe redaction, repeat optimization, and external history gates.",
    },
    {
      id: "ritual_autopilot_center",
      label: "Swiggy Ritual Autopilot Center",
      path: "/api/swiggy-ritual-autopilot-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns recurring household routines into consented Food, Instamart, Dineout, and combined plans with reminder-only cadence, fresh reads, and no automatic commercial actions.",
    },
    {
      id: "payment_truth_center",
      label: "Swiggy Payment Truth Center",
      path: "/api/swiggy-payment-truth-center",
      category: "api",
      status: "ready",
      evidence:
        "Reconciles Food cart totals, coupons, COD, Instamart checkout bills, Dineout free bookings, and paid-cart gates from Swiggy source-of-truth readbacks without storing payment instruments.",
    },
    {
      id: "meal_window_intelligence",
      label: "Swiggy Meal Window Intelligence",
      path: "/api/swiggy-meal-window-intelligence",
      category: "api",
      status: "ready",
      evidence:
        "Forecasts when to order, cook, reserve, track, or wait with fresh-read timing gates, no scheduled Food orders, tracking cadence caps, and advisory-only ETA risk buckets.",
    },
    {
      id: "customization_studio",
      label: "Swiggy Customization Studio",
      path: "/api/swiggy-customization-studio",
      category: "api",
      status: "ready",
      evidence:
        "Turns Food add-ons, menu variants, Instamart pack sizes, allergy cautions, voice-safe choice limits, and post-mutation cart readbacks into a visible customization safety layer.",
    },
    {
      id: "nutrition_budget_intelligence",
      label: "Nutrition & Budget Intelligence",
      path: "/api/nutrition-budget-intelligence",
      category: "api",
      status: "ready",
      evidence:
        "Optimizes protein-per-rupee, coupon-safe Food carts, Instamart pantry gaps, group budgets, and Dineout balance routes with nutrition safety controls.",
    },
    {
      id: "household_preference_graph",
      label: "Household Preference Graph",
      path: "/api/household-preference-graph",
      category: "api",
      status: "ready",
      evidence:
        "Maps consented Food active orders, Instamart go-to items and order history, Dineout saved-location signals, household weights, forecasts, automations, and retention rules.",
    },
    {
      id: "guest_collaboration_calendar",
      label: "Guest Collaboration & Calendar Center",
      path: "/api/guest-collaboration-calendar",
      category: "api",
      status: "ready",
      evidence:
        "Coordinates guest votes, occasion templates, Dineout slots, Food reminders, Instamart prep, calendar handoffs, Slack/Teams gates, and voice-safe briefs.",
    },
    {
      id: "luxury_experience_workspace",
      label: "Luxury Experience Workspace",
      path: "/api/luxury-experience-workspace",
      category: "api",
      status: "ready",
      evidence:
        "Productizes polished reservation, Food cart, Instamart basket, combined evening, and recovery review workspaces with all 35 Swiggy tools, concierge modes, widget fallbacks, voice contracts, telemetry, and confirmation controls.",
    },
    {
      id: "reviewer_artifact_vault",
      label: "Reviewer Artifact Vault",
      path: "/api/reviewer-artifact-vault",
      category: "api",
      status: "ready",
      evidence:
        "Packages proof links, OpenAPI, smoke commands, screenshot targets, demo-video checklist, logs, traces, redaction rules, support context, and Swiggy handoff copy into one reviewer manifest.",
    },
    {
      id: "review_decision",
      label: "Swiggy Builders Review Decision Center",
      path: "/api/swiggy-builders-review-decision",
      category: "api",
      status: "ready",
      evidence:
        "Turns official review signals into access-approval gates, recommendation, reviewer questions, proof links, operator-owned inputs, source-review watches, and Swiggy-owned go-live gates.",
    },
    {
      id: "demo_evidence_director",
      label: "Swiggy Demo Evidence Director",
      path: "/api/swiggy-demo-evidence-director",
      category: "api",
      status: "ready",
      evidence:
        "Coordinates the 2-3 minute demo storyboard, proof assets, recording gates, redaction checks, runbook commands, and builders@swiggy.in handoff copy.",
    },
    {
      id: "showcase_submission_center",
      label: "Swiggy Showcase Submission Center",
      path: "/api/swiggy-showcase-submission-center",
      category: "api",
      status: "ready",
      evidence:
        "Packages feature-ready pitch blocks, demo storyboard, metric proof, visual-gallery links, and builders@swiggy.in outreach copy while keeping video hosting, email sending, co-branding, and showcase approval externally gated.",
    },
    {
      id: "partner_support_room",
      label: "Swiggy Partner Support Room",
      path: "/api/swiggy-partner-support-room",
      category: "api",
      status: "ready",
      evidence:
        "Composes report_error readiness, support channels, S0-S3 incident lanes, evidence attachments, escalation runbook, capacity email, and enterprise support gates.",
    },
    {
      id: "access_evidence_matrix",
      label: "Swiggy Access Evidence Matrix",
      path: "/api/swiggy-access-evidence-matrix",
      category: "api",
      status: "ready",
      evidence:
        "Ties every official access field, review check, ground rule, legal item, attachment, browser step, proof command, owner, and external gate to MealPilot evidence.",
    },
    {
      id: "visual_qa_center",
      label: "Visual QA Center",
      path: "/api/visual-qa-center",
      category: "api",
      status: "ready",
      evidence:
        "Maps demo-critical UI screenshots, viewport targets, selector manifests, text-fit/no-overlap rules, widget fallback checks, mobile layout checks, and screenshot automation gates.",
    },
    {
      id: "builders_site_parity",
      label: "Swiggy Builders Site Parity",
      path: "/api/swiggy-builders-site-parity",
      category: "api",
      status: "ready",
      evidence:
        "Fetches the live Builders homepage, extracts anchors, llms alternates, CTA/source/footer/legal links, and reconciles them against Website Atlas before reviewer submission.",
    },
    {
      id: "builders_page_mesh",
      label: "Swiggy Builders Page Mesh",
      path: "/api/swiggy-builders-page-mesh",
      category: "api",
      status: "ready",
      evidence:
        "Fetches every non-external Builders page, validates page titles, anchors, module and CTA parity, approved origins, and safe public-page integrity.",
    },
    {
      id: "cta_live_audit",
      label: "CTA Live Audit",
      path: "/api/swiggy-cta-live-audit",
      category: "api",
      status: "ready",
      evidence:
        "Safely probes official Builders/docs click targets while keeping form, email, and legal CTAs as manual browser gates with drift classifications.",
    },
    {
      id: "interaction_qa",
      label: "Swiggy Interaction QA Center",
      path: "/api/swiggy-interaction-qa-center",
      category: "api",
      status: "ready",
      evidence:
        "Maps every executable portal CTA to route contracts, visible feedback, automation proof, dry-run rehearsals, and explicit Swiggy/operator gates.",
    },
    {
      id: "source_freeze_diff",
      label: "Swiggy Source Freeze Diff",
      path: "/api/swiggy-source-freeze-diff",
      category: "api",
      status: "ready",
      evidence:
        "Composes live page mesh, Website Atlas counts, llms/docs coverage, 35-tool parity, access evidence, builder packet export, and browser re-browse gates into the final pre-submission source freeze.",
    },
    {
      id: "access_submission_rehearsal",
      label: "Access Submission Rehearsal",
      path: "/api/access-submission-studio/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Dry-runs the official access-form packet with operator inputs, attachments, browser runbook, generated mailto handoff, and explicit Swiggy-owned submit gates.",
    },
    {
      id: "reviewer_packet_composer",
      label: "Reviewer Artifact Packet Composer",
      path: "/api/reviewer-artifact-vault/compose",
      category: "api",
      status: "ready",
      evidence:
        "Builds safe reviewer packets by section, channel, audience, screenshots, demo-video, and credential-gate choices without attaching secrets.",
    },
    {
      id: "visual_qa_rehearsal",
      label: "Visual QA Rehearsal",
      path: "/api/visual-qa-center/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Turns screenshot target groups, viewport choices, widget inclusion, and manual attachment readiness into capture commands and layout proof gates.",
    },
    {
      id: "docs_coverage_drill",
      label: "Docs Coverage Drill",
      path: "/api/swiggy-docs-coverage/drill",
      category: "api",
      status: "ready",
      evidence:
        "Rehearses selected llms.txt documentation sections with rendered twins, retrieval commands, proof links, and credential/drift gates.",
    },
    {
      id: "docs_twin_rehearsal",
      label: "Docs Twin Rehearsal",
      path: "/api/swiggy-docs-twin-explorer/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Builds markdown/rendered-page proof packets for official Swiggy docs twins, retrieval lanes, drift gates, and reviewer evidence.",
    },
    {
      id: "llms_manifest_rehearsal",
      label: "llms Manifest Rehearsal",
      path: "/api/swiggy-llms-manifest-verifier/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Exercises live-fetch, Docs Coverage fallback, and tool-parity modes with commands, telemetry, assertions, readiness decisions, and missing source gates.",
    },
    {
      id: "ai_client_validate_config",
      label: "AI Client Config Validation",
      path: "/api/ai-client-connect-kit/validate-config",
      category: "api",
      status: "ready",
      evidence:
        "Validates AI client MCP endpoint paths, Instamart /im routing, SDK auth mode, submitted-client gates, and secret redaction before handoff.",
    },
    {
      id: "brand_compliance_rehearsal",
      label: "Brand Compliance Rehearsal",
      path: "/api/brand-compliance-kit/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Dry-runs Powered by Swiggy attribution, co-branding boundaries, no-endorsement copy, asset gates, and launch screenshot checklist.",
    },
    {
      id: "interaction_qa_rehearsal",
      label: "Interaction QA Rehearsal",
      path: "/api/swiggy-interaction-qa-center/rehearse",
      category: "api",
      status: "ready",
      evidence:
        "Generates local CTA dry-run packets with route contracts, browser actions, expected feedback, automation proof, and external Swiggy gates.",
    },
    {
      id: "source_freeze_rehearsal",
      label: "Source Freeze Rehearsal",
      path: "/api/swiggy-source-freeze-diff/freeze",
      category: "api",
      status: "ready",
      evidence:
        "Re-runs pre-demo, pre-access-submission, and post-source-change freeze gates with metadata-only browser re-browse receipts.",
    },
    {
      id: "growth_partnership_composer",
      label: "Growth Partnership Composer",
      path: "/api/swiggy-growth-partnership/compose",
      category: "api",
      status: "ready",
      evidence:
        "Builds launch-experiment, metrics, proof-asset, co-marketing, and builders@swiggy.in partner ask packets while preserving approval gates.",
    },
    {
      id: "partner_success_composer",
      label: "Partner Success Composer",
      path: "/api/swiggy-partner-success-desk/compose",
      category: "api",
      status: "ready",
      evidence:
        "Composes support, quota, incident, growth, enterprise, escalation, and partner-manager handoff packets with operator and Swiggy gates.",
    },
    {
      id: "showcase_submission_composer",
      label: "Showcase Submission Composer",
      path: "/api/swiggy-showcase-submission-center/compose",
      category: "api",
      status: "ready",
      evidence:
        "Packages pitch copy, demo storyboard, metric pack, visual gallery, outreach copy, and showcase approval gates for the final Send Us a Demo path.",
    },
    {
      id: "channel_multimodal_composer",
      label: "Channel & Multimodal Composer",
      path: "/api/channel-multimodal-studio/compose",
      category: "api",
      status: "ready",
      evidence:
        "Builds voice, web chat, Slack/Teams, mobile camera, enterprise, and screenshot-to-order execution packets with route and confirmation gates.",
    },
    {
      id: "nutrition_budget_advisor",
      label: "Nutrition & Budget Advisor",
      path: "/api/nutrition-budget-intelligence/advise",
      category: "api",
      status: "ready",
      evidence:
        "Dry-runs protein-per-rupee, coupon-safe carts, Instamart pantry gaps, group budgets, Dineout balance, and nutrition-data gates.",
    },
    {
      id: "household_preference_simulator",
      label: "Household Preference Simulator",
      path: "/api/household-preference-graph/simulate",
      category: "api",
      status: "ready",
      evidence:
        "Simulates consented Food, Instamart, Dineout, household-weight, forecast, privacy, and external history gates without raw payload storage.",
    },
    {
      id: "guest_collaboration_composer",
      label: "Guest Collaboration Composer",
      path: "/api/guest-collaboration-calendar/compose",
      category: "api",
      status: "ready",
      evidence:
        "Builds guest vote, occasion, Dineout-first, Food reminder, Instamart prep, calendar, Slack/Teams, and no-scheduled-delivery packets.",
    },
    {
      id: "luxury_experience_composer",
      label: "Luxury Experience Composer",
      path: "/api/luxury-experience-workspace/compose",
      category: "api",
      status: "ready",
      evidence:
        "Composes premium Dineout, Food, Instamart, combined-evening, and recovery workspaces with all-tool coverage, widget fallback, and confirmation boundaries.",
    },
    {
      id: "docs_coverage",
      label: "Swiggy Docs Coverage",
      path: "/api/swiggy-docs-coverage",
      category: "api",
      status: "ready",
      evidence: "Maps all llms.txt-linked docs pages to MealPilot evidence, expansion lanes, and external gates.",
    },
    {
      id: "docs_twin_explorer",
      label: "Swiggy Docs Twin Explorer",
      path: "/api/swiggy-docs-twin-explorer",
      category: "api",
      status: "ready",
      evidence:
        "Pairs every official llms.txt markdown twin with its rendered page, section group, retrieval lane, MealPilot proof route, and drift gate.",
    },
    {
      id: "upstream_watch",
      label: "Swiggy Upstream Watch",
      path: "/api/swiggy-upstream-watch",
      category: "api",
      status: "ready",
      evidence:
        "Tracks llms.txt, llms-full.txt, v1.0 changelog, v1.1/v1.2/v2 roadmap, signed manifest watch, and action queue for future Swiggy MCP changes.",
    },
    {
      id: "source_intelligence",
      label: "Swiggy Source Intelligence",
      path: "/api/swiggy-source-intelligence",
      category: "api",
      status: "ready",
      evidence:
        "Reconciles Swiggy website pages, CTAs, llms docs, markdown twins, 35 MCP tools, source drift signals, build queue, and external credential gates in one reviewer surface.",
    },
    {
      id: "innovation_radar",
      label: "Swiggy Innovation Radar",
      path: "/api/swiggy-innovation-radar",
      category: "api",
      status: "ready",
      evidence:
        "Turns Swiggy developer ideas, enterprise signals, access ground rules, support model, and all MCP servers into premium MealPilot opportunity lanes, route optimizations, build phases, and partner gates.",
    },
    {
      id: "ai_client_connect",
      label: "AI Client Connect Kit",
      path: "/api/ai-client-connect-kit",
      category: "api",
      status: "ready",
      evidence: "Generates Swiggy MCP configs for AI clients, coding-agent rules, SDK auth modes, and delegated-auth gates.",
    },
    {
      id: "coding_agent_governance",
      label: "Coding Agent Governance",
      path: "/api/coding-agent-governance",
      category: "api",
      status: "ready",
      evidence:
        "Reads the repo AGENTS.md and official Swiggy coding-agent docs to preserve source-first MCP edits, no fabricated tools, confirmation gates, and no-token/no-PII logging rules.",
    },
    {
      id: "mcp_gateway",
      label: "MCP Gateway",
      path: "/api/mcp-gateway",
      category: "runtime",
      status: "ready",
      evidence:
        "Shows localhost mock routing, staging/production Streamable HTTP cutover posture, OAuth token presence, fail-closed behavior, and per-server endpoint readiness.",
    },
    {
      id: "handshake_doctor",
      label: "Swiggy Handshake Doctor",
      path: "/api/mcp/handshake-doctor",
      category: "runtime",
      status: "ready",
      evidence:
        "Runs safe OAuth metadata and Food, Instamart, and Dineout MCP endpoint probes without bearer tokens, tools/call, or commercial actions.",
    },
    {
      id: "llms_manifest_verifier",
      label: "Swiggy llms Manifest Verifier",
      path: "/api/swiggy-llms-manifest-verifier",
      category: "api",
      status: "ready",
      evidence:
        "Parses the official llms.txt manifest or disclosed Docs Coverage fallback, verifies rendered twins, Swiggy-only origins, and Food 14 / Instamart 13 / Dineout 8 reference counts.",
    },
    {
      id: "tool_parity_auditor",
      label: "Swiggy Tool Parity Auditor",
      path: "/api/swiggy-tool-parity-auditor",
      category: "api",
      status: "ready",
      evidence:
        "Matches live official reference tools against MealPilot contracts, fixtures, route classes, confirmation gates, retry posture, and 35/35 parity evidence.",
    },
    {
      id: "journey_compiler",
      label: "Swiggy Journey Compiler",
      path: "/api/swiggy-journey-compiler",
      category: "api",
      status: "ready",
      evidence: "Compiles official Food, Instamart, Dineout, combined, and premium three-server journeys with all 35 tools indexed.",
    },
    {
      id: "access_dossier",
      label: "Swiggy Access Dossier",
      path: "/api/swiggy-access-dossier",
      category: "api",
      status: "ready",
      evidence: "Maps production-access fields, review checks, ground rules, legal readiness, tracks, proof links, manual inputs, and external gates.",
    },
    {
      id: "use_case_studio",
      label: "Premium Use Case Studio",
      path: "/api/premium-use-case-studio",
      category: "api",
      status: "ready",
      evidence: "Packages ten premium MealPilot playbooks with all 35 Swiggy tools placed into optimized, confirmation-safe routes.",
    },
    {
      id: "premium_concierge_itinerary",
      label: "Premium Concierge Itinerary",
      path: "/api/premium-concierge-itinerary",
      category: "api",
      status: "ready",
      evidence:
        "Turns official Food, Instamart, Dineout, and combined Swiggy recipes into a premium day-and-weekend itinerary with route optimizations, confirmations, and reminders.",
    },
    {
      id: "staging_certification",
      label: "Staging Certification Matrix",
      path: "/api/staging-certification-matrix",
      category: "api",
      status: "ready",
      evidence:
        "Groups all 35 Swiggy tools into credentialed staging smoke waves with OAuth/DCR, 48-hour soak, telemetry, rollback, and production promotion gates.",
    },
    {
      id: "brand_compliance",
      label: "Brand Compliance Kit",
      path: "/api/brand-compliance-kit",
      category: "api",
      status: "ready",
      evidence:
        "Maps Powered by Swiggy attribution, co-branding rules, asset gates, palette usage, no-endorsement copy, and launch screenshot checklist.",
    },
    {
      id: "data_governance",
      label: "Data Governance Center",
      path: "/api/data-governance-center",
      category: "api",
      status: "ready",
      evidence:
        "Maps Swiggy DPDP roles, India/Singapore residency, tool-call PII flows, DSR routing, 90-day audit logs, token redaction, and signed-manifest watch items.",
    },
    {
      id: "enterprise_delegated_auth",
      label: "Enterprise Delegated Auth Center",
      path: "/api/enterprise-delegated-auth",
      category: "api",
      status: "ready",
      evidence:
        "Models Swiggy enterprise on-behalf-of OAuth 2.1 PKCE, per-user token lifecycle, redirect schemes, troubleshooting, architecture review, and platform-operator gates.",
    },
    {
      id: "traffic_readiness",
      label: "Traffic Readiness Plan",
      path: "/api/traffic-readiness-plan",
      category: "runtime",
      status: "ready",
      evidence:
        "Packages expected volume, per-lane traffic budgets, Retry-After behavior, seven-day launch notice, capacity-upgrade email, and 1%-to-100% rollout gates.",
    },
    {
      id: "backpressure_governor",
      label: "MCP Backpressure Governor",
      path: "/api/mcp/backpressure-governor",
      category: "runtime",
      status: "ready",
      evidence:
        "Turns Swiggy planned rate-limit guidance into token buckets, queue discipline, Retry-After handling, voice burst shaping, tracking cadence, and background-job gates.",
    },
    {
      id: "load_lab",
      label: "Swiggy Load Lab",
      path: "/api/swiggy-load-lab",
      category: "runtime",
      status: "ready",
      evidence:
        "Composes Traffic Readiness, Backpressure Governor, and Route Optimizer into synthetic launch-load scenarios, cohort ramps, Retry-After drills, and capacity gates.",
    },
    {
      id: "quota_negotiation",
      label: "Swiggy Quota Negotiation Center",
      path: "/api/swiggy-quota-negotiation-center",
      category: "runtime",
      status: "ready",
      evidence:
        "Packages pilot and campaign capacity asks, QPS forecasts, Retry-After readiness, route optimization, and a builders@swiggy.in capacity request packet.",
    },
    {
      id: "offer_intelligence",
      label: "Swiggy Offer Intelligence",
      path: "/api/swiggy-offer-intelligence",
      category: "api",
      status: "ready",
      evidence:
        "Turns Food coupon tools, Dineout deal discovery, Instamart value substitution, and offer-copy gates into confirmation-safe savings evidence.",
    },
    {
      id: "order_lifecycle",
      label: "Swiggy Order Lifecycle",
      path: "/api/swiggy-order-lifecycle",
      category: "runtime",
      status: "ready",
      evidence:
        "Maps Food, Instamart, and Dineout status tools into post-confirmation timelines, non-blind retry probes, tracking cadence, telemetry, and support-ready recovery.",
    },
    {
      id: "location_trust",
      label: "Swiggy Location Trust",
      path: "/api/swiggy-location-trust",
      category: "api",
      status: "ready",
      evidence:
        "Covers Food and Instamart saved-address tools, Dineout saved locations, user-choice pauses, address switch refresh guards, raw-address redaction, and staging credential gates.",
    },
    {
      id: "cart_mutation_workbench",
      label: "Swiggy Cart Mutation Workbench",
      path: "/api/swiggy-cart-mutation-workbench",
      category: "api",
      status: "ready",
      evidence:
        "Makes Food cart readbacks, Instamart full-cart replacement, Dineout create_cart gates, payment-method truth, add-on confirmation, and staging cart-write gates reviewer-visible.",
    },
    {
      id: "discovery_freshness",
      label: "Swiggy Discovery Freshness",
      path: "/api/swiggy-discovery-freshness",
      category: "api",
      status: "ready",
      evidence:
        "Turns Food restaurant/menu search, Instamart product/go-to discovery, Dineout search/details/slots, pagination, variant truth, coordinate consistency, and freshness invalidation into reviewer evidence.",
    },
    {
      id: "confirmation_command_center",
      label: "Swiggy Confirmation Command Center",
      path: "/api/swiggy-confirmation-command-center",
      category: "api",
      status: "ready",
      evidence:
        "Makes final Food place_food_order, Instamart checkout, Dineout book_table, separate combined approvals, post-action status probes, payment truth, and live credential gates reviewer-visible.",
    },
    {
      id: "cancellation_care_center",
      label: "Swiggy Cancellation & Care Center",
      path: "/api/swiggy-cancellation-care-center",
      category: "api",
      status: "ready",
      evidence:
        "Separates Food and Instamart no-tool cancellation requests, official customer-care copy, Dineout booking status, report_error toolContext, and incident email routing.",
    },
    {
      id: "dineout_precision_center",
      label: "Swiggy Dineout Precision Center",
      path: "/api/swiggy-dineout-precision-center",
      category: "api",
      status: "ready",
      evidence:
        "Separates Dineout free reservations from bill-payment carts, validates isFree and bookingPrice before book_table, blocks paid deals, and keeps live payment evidence external-gated.",
    },
    {
      id: "slo_incident_command",
      label: "SLO Incident Command Center",
      path: "/api/slo-incident-command",
      category: "runtime",
      status: "ready",
      evidence:
        "Maps Swiggy 99.9% uptime targets, latency classes, status-page fallback, incident comms, 72-hour maintenance notice, measurement exclusions, and remediation path.",
    },
    {
      id: "tool_lab",
      label: "MCP Tool Lab",
      path: "/api/mcp/tool-lab",
      category: "api",
      status: "ready",
      evidence: "Probes all 35 Food, Instamart, and Dineout tools with JSON-RPC samples and safety gates.",
    },
    {
      id: "tool_contract_matrix",
      label: "Tool Contract Matrix",
      path: "/api/mcp/tool-contract-matrix",
      category: "api",
      status: "ready",
      evidence:
        "Lists every official Swiggy MCP tool with parameters, response envelope, retry policy, confirmation gate, error buckets, and fixture preview.",
    },
    {
      id: "scenario_runner",
      label: "Scenario Runner",
      path: "/api/mcp/scenario-runner",
      category: "api",
      status: "ready",
      evidence:
        "Executes official Food, Instamart, Dineout, and combined recipes as mock JSON-RPC traces with guard/recovery probes across all 35 tools.",
    },
    {
      id: "state_orchestrator",
      label: "State Orchestrator",
      path: "/api/mcp/state-orchestrator",
      category: "api",
      status: "ready",
      evidence:
        "Maps official multi-turn cart state, server-boundary, stale-cart recovery, and voice/chat response contracts into executable MealPilot guards.",
    },
    {
      id: "widget_runtime",
      label: "Widget Runtime Center",
      path: "/api/mcp/widget-runtime",
      category: "api",
      status: "ready",
      evidence:
        "Models Swiggy widget iframe contracts, sandboxing, origin verification, postMessage handlers, voice exclusions, opt-in gates, and semantic fallbacks.",
    },
    {
      id: "widget_experience_composer",
      label: "Swiggy Widget Experience Composer",
      path: "/api/swiggy-widget-experience-composer",
      category: "api",
      status: "ready",
      evidence:
        "Composes Swiggy widget runtime surfaces into premium desktop, tablet, mobile, voice, and reviewer placements with fallback galleries and activation runbooks.",
    },
    {
      id: "hosted_widget_activation",
      label: "Swiggy Hosted Widget Activation Center",
      path: "/api/swiggy-hosted-widget-activation",
      category: "api",
      status: "ready",
      evidence:
        "Packages hosted widget parent-origin policy, iframe sandbox rules, postMessage handshakes, fallback parity, telemetry redaction, and Swiggy-owned hosted URL gates.",
    },
    {
      id: "agent_experience_benchmark",
      label: "Swiggy Agent Experience Benchmark",
      path: "/api/swiggy-agent-experience-benchmark",
      category: "api",
      status: "ready",
      evidence:
        "Benchmarks premium Swiggy journeys against speed, trust, personalization, multimodal continuity, resilience, commercial safety, UX acceptance criteria, and innovation moats.",
    },
    {
      id: "private_pilot_control_room",
      label: "Swiggy Private Pilot Control Room",
      path: "/api/swiggy-private-pilot-control-room",
      category: "api",
      status: "ready",
      evidence:
        "Turns benchmark journeys into private-pilot cohorts, consent artifacts, telemetry metrics, support paths, traffic gates, and staging credential handoff actions.",
    },
    {
      id: "staging_replay_center",
      label: "Swiggy Staging Replay Center",
      path: "/api/swiggy-staging-replay",
      category: "runtime",
      status: "ready",
      evidence:
        "Executes allowlisted safe replay probes in mock or credentialed staging mode, blocks commercial tools, records response hashes, and prepares builders@swiggy.in handoff proof.",
    },
    {
      id: "commercial_action_guard",
      label: "Commercial Action Guard",
      path: "/api/mcp/commercial-action-guard",
      category: "api",
      status: "ready",
      evidence:
        "Locks Food order placement, Instamart checkout, Dineout booking, and combined commercial flows behind fresh reads, explicit confirmations, check-then-retry drills, telemetry, and support packets.",
    },
    {
      id: "staging_cutover",
      label: "Staging Cutover Rehearsal",
      path: "/api/mcp/staging-cutover",
      category: "runtime",
      status: "ready",
      evidence:
        "Rehearses real Swiggy Streamable HTTP cutover with OAuth, first read-only probes, fail-closed token behavior, retry branches, support packet, and 48-hour staging gates.",
    },
    {
      id: "staging_credential_drill",
      label: "Swiggy Staging Credential Drill Center",
      path: "/api/swiggy-staging-credential-drill",
      category: "runtime",
      status: "ready",
      evidence:
        "Combines credential signal, first-call JSON-RPC drills, seeded-data requirements, operator runbook, handoff email, and Swiggy-owned promotion gates.",
    },
    {
      id: "credential_vault_center",
      label: "Swiggy Credential Vault Center",
      path: "/api/swiggy-credential-vault-center",
      category: "runtime",
      status: "ready",
      evidence:
        "Summarizes configured secret posture, no-token redaction rules, rotation runbooks, cutover checks, support-safe credential packets, and Swiggy-owned credential gates.",
    },
    {
      id: "staging_seed_smoke",
      label: "Swiggy Staging Seed & Smoke Center",
      path: "/api/swiggy-staging-seed-smoke-center",
      category: "runtime",
      status: "ready",
      evidence:
        "Maps Food, Instamart, and Dineout seeded fixtures to read, mutation, commercial, support, telemetry, and promotion smoke waves before live credential use.",
    },
    {
      id: "live_signal_calibration",
      label: "Swiggy Live Signal Calibration Center",
      path: "/api/swiggy-live-signal-calibration",
      category: "runtime",
      status: "ready",
      evidence:
        "Reconciles local personalization, discovery, offer, order, location, and support signals against future Food, Instamart, and Dineout staging reads with privacy and drift gates.",
    },
    {
      id: "capability_registry",
      label: "MCP Capability Registry",
      path: "/api/mcp/capability-registry",
      category: "api",
      status: "ready",
      evidence: "Unifies tools, resources, prompts, OAuth metadata, widgets, and external gates.",
    },
    {
      id: "resource_prompt_studio",
      label: "Resource & Prompt Studio",
      path: "/api/mcp/resource-prompt-studio",
      category: "api",
      status: "ready",
      evidence:
        "Exercises resources/list, resources/read, prompts/list, and prompts/get across Food, Instamart, and Dineout with local samples and live Swiggy gates.",
    },
    {
      id: "credential_cockpit",
      label: "Credential Cockpit",
      path: "/api/credential-onboarding",
      category: "api",
      status: "ready",
      evidence: "Shows OAuth metadata, Dynamic Client Registration preview, redirect audit, scopes, and external gates.",
    },
    {
      id: "credential_handoff_center",
      label: "Credential Handoff Center",
      path: "/api/swiggy-credential-handoff-center",
      category: "api",
      status: "ready",
      evidence:
        "Unifies localhost proof, DCR, OAuth PKCE, exact redirect URI, secret vault, staging credentials, seeded smoke, 48-hour soak, and production promotion gates.",
    },
    {
      id: "credential_readiness_dossier",
      label: "Swiggy Credential Readiness Dossier",
      path: "/api/swiggy-credential-readiness-dossier",
      category: "api",
      status: "ready",
      evidence:
        "Joins source-freeze posture, public homepage signals, 35-tool manifest certification, redacted issuance receipt state, DCR, vault, staging credentials, seeded users, proof commands, and production-promotion gates.",
    },
    {
      id: "sandbox_credential_workbench",
      label: "Sandbox Credential Workbench",
      path: "/api/sandbox-credential-workbench",
      category: "api",
      status: "ready",
      evidence:
        "Joins localhost demo proof, DCR, PKCE, redirect allowlisting, staging credentials, seeded data, 48-hour soak, and production-promotion gates.",
    },
    {
      id: "oauth_status",
      label: "Swiggy OAuth Status",
      path: "/api/auth/swiggy/status",
      category: "api",
      status: "ready",
      evidence:
        "Exposes redacted OAuth lifecycle state, authorize/token/logout endpoints, pending PKCE verifier count, callback outcome, token source, storage policy, and exact-match redirect posture.",
    },
    {
      id: "auth_lifecycle_center",
      label: "Swiggy Auth Lifecycle Center",
      path: "/api/swiggy-auth-lifecycle-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns PKCE, 120-second codes, 5-day tokens, no refresh-token assumption, 401/419 re-auth, exact redirects, per-user tokens, and no-token logging into reviewer evidence.",
    },
    {
      id: "enterprise_platform_center",
      label: "Swiggy Enterprise Platform Center",
      path: "/api/enterprise-platform-center",
      category: "api",
      status: "ready",
      evidence:
        "Turns platform-operator onboarding, tenant boundaries, delegated auth, quota review, contract support, audit exports, staging soak, and co-branding gates into reviewer evidence.",
    },
    {
      id: "runtime_telemetry",
      label: "Runtime Telemetry",
      path: "/api/telemetry/runtime",
      category: "runtime",
      status: "ready",
      evidence: "Captures request IDs, hashed user context, status classes, durations, and session IDs without raw PII.",
    },
    {
      id: "audit_ledger",
      label: "Audit Ledger Center",
      path: "/api/audit-ledger",
      category: "runtime",
      status: "ready",
      evidence:
        "Aggregates redacted plan audit events, Swiggy session support correlation, retention posture, DSR routing, and support packet fields.",
    },
    {
      id: "health_check",
      label: "Health Check",
      path: "/api/health",
      category: "runtime",
      status: "ready",
      evidence: "Exposes process-level health for reviewer smoke checks and local production readiness.",
    },
    {
      id: "readiness_check",
      label: "Readiness Check",
      path: "/api/ready",
      category: "runtime",
      status: "ready",
      evidence: "Reports API/static serving, storage mode, scope, session count, and 35/35 Swiggy MCP coverage.",
    },
    {
      id: "runtime_config",
      label: "Runtime Config",
      path: "/api/config",
      category: "runtime",
      status: "ready",
      evidence: "Shows redacted runtime configuration, mock/staging posture, OAuth scope, redirect URI, and feature availability.",
    },
    {
      id: "privacy_delete",
      label: "Privacy Delete",
      path: "/api/privacy",
      category: "api",
      status: "ready",
      evidence: "Provides local DSR deletion behavior for MealPilot-held sessions while preserving Swiggy-owned data boundaries.",
    },
    {
      id: "privacy_export",
      label: "Privacy Export",
      path: "/api/privacy/export",
      category: "api",
      status: "ready",
      evidence: "Exports MealPilot-held session data for DSR review without raw Swiggy payloads, secrets, or payment data.",
    },
    {
      id: "storage_status",
      label: "Storage Status",
      path: "/api/storage/status",
      category: "runtime",
      status: "ready",
      evidence: "Reports memory/durable storage mode, stored sessions, compaction posture, and backup readiness.",
    },
    {
      id: "storage_export",
      label: "Storage Export",
      path: "/api/storage/export",
      category: "runtime",
      status: "ready",
      evidence: "Exports support-safe local storage snapshots for reviewer backup and restore drills.",
    },
    {
      id: "storage_compact",
      label: "Storage Compact",
      path: "/api/storage/compact",
      category: "runtime",
      status: "ready",
      evidence: "Compacts local stored sessions and proves data-retention controls without touching Swiggy systems.",
    },
    {
      id: "storage_restore",
      label: "Storage Restore",
      path: "/api/storage/restore",
      category: "runtime",
      status: "ready",
      evidence: "Restores support-safe local storage exports to prove backup recovery and reviewer reproducibility.",
    },
    {
      id: "reviewer_proof",
      label: "Reviewer Proof",
      path: "/api/reviewer-proof",
      category: "api",
      status: "ready",
      evidence: "Aggregates proof score, launch evidence, telemetry posture, screenshot status, and Swiggy submission readiness.",
    },
    {
      id: "evaluation_lab",
      label: "Evaluation Lab",
      path: "/api/evaluation-lab",
      category: "api",
      status: "ready",
      evidence: "Runs persona and scenario QA for route quality, action safety, privacy posture, and premium experience acceptance.",
    },
    {
      id: "submission_package",
      label: "Submission Package",
      path: "/api/submission-package",
      category: "api",
      status: "ready",
      evidence: "Packages Swiggy application fields, proof links, attachments, support context, and external gates.",
    },
    {
      id: "demo_studio",
      label: "Demo Studio",
      path: "/api/demo-studio",
      category: "api",
      status: "ready",
      evidence: "Curates the two-to-three-minute demo script, scenes, proof assets, and operator-owned video gates.",
    },
    {
      id: "support_bridge_report",
      label: "Support Bridge Report",
      path: "/api/support/bridge/report",
      category: "api",
      status: "ready",
      evidence: "Executes consent-gated report_error payload drills with redacted context, receipts, SLA routing, and escalation fields.",
    },
    {
      id: "session_readback",
      label: "Session Readback",
      path: "/api/sessions/{sessionId}",
      category: "runtime",
      status: "ready",
      evidence: "Reads one session's plan, recommendations, confirmations, audit ids, and support correlation for reviewer replay.",
    },
    {
      id: "session_preflight",
      label: "Session Preflight",
      path: "/api/sessions/{sessionId}/preflight",
      category: "runtime",
      status: "ready",
      evidence: "Runs stale-data, confirmation, route, and safety preflight checks before any Swiggy commercial action.",
    },
    {
      id: "session_replay",
      label: "Session Replay",
      path: "/api/sessions/{sessionId}/replay",
      category: "runtime",
      status: "ready",
      evidence: "Replays session evidence with redacted tool calls, route decisions, and non-blind retry posture.",
    },
    {
      id: "session_widgets",
      label: "Session Widgets",
      path: "/api/sessions/{sessionId}/widgets",
      category: "runtime",
      status: "ready",
      evidence: "Shows widget render contracts, fallback states, and session-scoped postMessage readiness.",
    },
    {
      id: "session_staging_transcript",
      label: "Session Staging Transcript",
      path: "/api/sessions/{sessionId}/staging-transcript",
      category: "runtime",
      status: "ready",
      evidence: "Exports Swiggy-ready JSONL and Markdown replay with redaction manifest, support envelope, and certification-wave mapping.",
    },
    {
      id: "planner_api",
      label: "Planner API",
      path: "/api/plan",
      category: "api",
      status: "ready",
      evidence: "Creates the core MealPilot plan that exercises Food, Instamart, Dineout, route optimization, telemetry, and support evidence.",
    },
    {
      id: "confirmation_api",
      label: "Confirmation API",
      path: "/api/confirm",
      category: "api",
      status: "ready",
      evidence: "Executes a single explicit confirmation path while preserving commercial-action safety boundaries.",
    },
    {
      id: "confirm_all_api",
      label: "Confirm All API",
      path: "/api/confirm-all",
      category: "api",
      status: "ready",
      evidence: "Exercises batch confirmation safety with explicit user intent, preflight proof, and support/audit correlation.",
    },
    {
      id: "go_live",
      label: "Go Live Checklist",
      path: "/api/go-live",
      category: "api",
      status: "ready",
      evidence: "Lists Swiggy production promotion checks, approval gates, traffic posture, observability, and rollback readiness.",
    },
    {
      id: "submission_console",
      label: "Submission Console",
      path: "/api/submission-console",
      category: "api",
      status: "ready",
      evidence:
        "Consolidates official developer/enterprise form targets, prepared access fields, proof attachments, runbook steps, blockers, and handoff drafts.",
    },
    {
      id: "access_submission_studio",
      label: "Access Submission Studio",
      path: "/api/access-submission-studio",
      category: "api",
      status: "ready",
      evidence:
        "Turns Start Building, Request access, and Send Us a Demo into copy-ready form values, required attachments, browser runbook steps, mailto handoff, saved operator state, and non-auto-submission rehearsals.",
    },
    {
      id: "submission_timeline_center",
      label: "Swiggy Submission Timeline Center",
      path: "/api/swiggy-submission-timeline-center",
      category: "api",
      status: "ready",
      evidence:
        "Sequences proof freeze, demo recording, Request Access, Send Demo, DCR, staging seed, 48-hour soak, partner success, and production promotion with explicit MealPilot, operator, and Swiggy ownership.",
    },
    {
      id: "partner_success_desk",
      label: "Swiggy Partner Success Desk",
      path: "/api/swiggy-partner-success-desk",
      category: "api",
      status: "ready",
      evidence:
        "Composes access handoff, developer support, SLO incidents, capacity review, backpressure, growth showcase asks, escalation emails, and enterprise Slack/partner-manager gates into one post-access operator room.",
    },
    {
      id: "builder_packet_export",
      label: "Builder Packet Export",
      path: "/api/builder-packet-export",
      category: "api",
      status: "ready",
      evidence:
        "Generates copy-ready Markdown and machine-readable JSON packet artifacts with form fields, attachments, commands, handoff email, and explicit operator/Swiggy gates.",
    },
    {
      id: "trace_monitor",
      label: "Trace Monitor",
      path: "/api/observability/traces",
      category: "runtime",
      status: "ready",
      evidence: "Converts plan audit trails into MCP spans with retry, cache, and redaction attributes.",
    },
    {
      id: "route_optimizer",
      label: "Route Optimizer",
      path: "/api/swiggy-route-optimizer",
      category: "api",
      status: "ready",
      evidence: "Documents call-saving routes, cache rules, non-blind retry policy, and staging assertions.",
    },
    {
      id: "resilience",
      label: "Resilience Lab",
      path: "/api/resilience",
      category: "api",
      status: "ready",
      evidence: "Exercises 5xx, 429, 401, non-idempotent recovery, and deprecation-monitoring drills.",
    },
    {
      id: "support_bridge",
      label: "Support Bridge",
      path: "/api/support/bridge",
      category: "api",
      status: "ready",
      evidence: "Prepares official report_error payloads, SLA routing, redaction rules, and escalation email.",
    },
    {
      id: "error_intelligence",
      label: "Error Intelligence",
      path: "/api/error-intelligence",
      category: "api",
      status: "ready",
      evidence: "Maps Swiggy success:false envelopes, retry buckets, planned codes, and terminal domain errors.",
    },
    {
      id: "reviewer_proof",
      label: "Reviewer Proof",
      path: "/api/reviewer-proof",
      category: "api",
      status: "ready",
      evidence: "Aggregates reviewer highlights, blockers, and artifact links into one proof score.",
    },
    {
      id: "builder_packet",
      label: "Builder Packet Markdown",
      path: "/api/builder-package.md",
      category: "doc",
      status: "ready",
      evidence: "Copy-ready application packet for Swiggy Builder Access review.",
    },
    {
      id: "latest_plan",
      label: "Latest Plan Session",
      path: latestPlan ? `/api/sessions/${latestPlan.id}` : "/api/plan",
      category: "api",
      status: latestPlan ? "ready" : "manual_input",
      evidence: latestPlan ? `${latestPlan.id} composes Food, Instamart, and Dineout.` : "Run a plan before recording the final demo.",
    },
    {
      id: "staging_transcript",
      label: "Staging Transcript Export",
      path: latestPlan ? `/api/sessions/${latestPlan.id}/staging-transcript` : "/api/sessions/:sessionId/staging-transcript",
      category: "api",
      status: latestPlan ? "ready" : "manual_input",
      evidence: latestPlan
        ? "Exports redacted JSONL and Markdown replay with session ids, request ids, retry policy, support envelope, and certification-wave mapping."
        : "Run a plan before exporting the staging transcript evidence.",
    },
    {
      id: "demo_video",
      label: "Demo Video URL",
      path: "Loom/Drive/YouTube unlisted URL",
      category: "external",
      status: "manual_input",
      evidence: "Swiggy asks builders to record a short localhost or staging flow video.",
    },
    {
      id: "staging_credentials",
      label: "Staging Credentials",
      path: "mcp-staging.swiggy.com",
      category: "external",
      status: "external_gate",
      evidence: "Issued by Swiggy during application review; required for real seeded-data verification.",
    },
  ];
}

function buildPhases(config: ServerConfig, latestPlan: MealPlan | undefined, artifacts: LaunchBundleArtifact[]): LaunchBundlePhase[] {
  const artifact = (id: string) => artifacts.find((item) => item.id === id)?.path ?? id;
  const productionRedirectReady = config.swiggyRedirectUri.startsWith("https://");

  return [
    {
      id: "local_review",
      label: "Local reviewer demo",
      status: latestPlan ? "ready" : "manual_input",
      owner: "MealPilot",
      evidence: latestPlan
        ? "A three-server plan exists and all local proof endpoints are available."
        : "Run a plan and confirm one action before recording.",
      artifacts: [
        artifact("latest_plan"),
        artifact("staging_transcript"),
        artifact("website_atlas"),
        artifact("module_intelligence"),
        artifact("journey_gates"),
        artifact("homepage_experience"),
        artifact("deep_site_map"),
        artifact("developer_quickstart"),
        artifact("cta_execution"),
        artifact("builder_intake"),
        artifact("faq_policy"),
        artifact("faq_resolution"),
        artifact("growth_partnership"),
        artifact("talent_signal"),
        artifact("conversion_center"),
        artifact("benefits_activation"),
        artifact("channel_multimodal_studio"),
        artifact("visual_dish_capture"),
        artifact("voice_commerce_center"),
        artifact("quality_loop_center"),
        artifact("nutrition_budget_intelligence"),
        artifact("household_preference_graph"),
        artifact("guest_collaboration_calendar"),
        artifact("luxury_experience_workspace"),
        artifact("reviewer_artifact_vault"),
        artifact("review_decision"),
        artifact("access_evidence_matrix"),
        artifact("visual_qa_center"),
        artifact("submission_console"),
        artifact("docs_twin_explorer"),
        artifact("upstream_watch"),
        artifact("source_intelligence"),
        artifact("innovation_radar"),
        artifact("premium_concierge_itinerary"),
        artifact("tool_lab"),
        artifact("tool_contract_matrix"),
        artifact("scenario_runner"),
        artifact("state_orchestrator"),
        artifact("widget_runtime"),
        artifact("commercial_action_guard"),
        artifact("live_signal_calibration"),
        artifact("backpressure_governor"),
        artifact("load_lab"),
        artifact("offer_intelligence"),
        artifact("order_lifecycle"),
        artifact("staging_cutover"),
        artifact("capability_registry"),
        artifact("resource_prompt_studio"),
        artifact("oauth_status"),
        artifact("runtime_telemetry"),
        artifact("audit_ledger"),
        artifact("slo_incident_command"),
        artifact("data_governance"),
        artifact("enterprise_delegated_auth"),
      ],
    },
    {
      id: "access_application",
      label: "Builder Access application",
      status: "manual_input",
      owner: "Operator",
      evidence: "Application fields are prepared; final contact email, video URL, and production redirect must be supplied.",
      artifacts: [
        artifact("builder_packet"),
        artifact("submission_console"),
        artifact("credential_cockpit"),
        artifact("credential_handoff_center"),
        artifact("oauth_status"),
        artifact("enterprise_delegated_auth"),
        artifact("traffic_readiness"),
        artifact("backpressure_governor"),
        artifact("load_lab"),
        artifact("offer_intelligence"),
        artifact("order_lifecycle"),
        artifact("demo_video"),
        artifact("staging_credential_drill"),
        artifact("live_signal_calibration"),
      ],
    },
    {
      id: "staging_cutover",
      label: "Staging cutover",
      status: hasClientId(config) ? "manual_input" : "external_gate",
      owner: "Swiggy",
      evidence: hasClientId(config)
        ? "Client identity is configured; complete OAuth and run seeded-data smoke."
        : "Await staging credentials or live Dynamic Client Registration approval.",
      artifacts: [
        artifact("staging_credentials"),
        artifact("staging_certification"),
        artifact("staging_cutover"),
        artifact("staging_credential_drill"),
        artifact("live_signal_calibration"),
        "/api/mcp-gateway",
        "/api/telemetry/runtime",
        artifact("audit_ledger"),
      ],
    },
    {
      id: "production_promotion",
      label: "Production promotion",
      status: productionRedirectReady && config.swiggyMode === "production" ? "manual_input" : "external_gate",
      owner: "Swiggy",
      evidence: "Production requires HTTPS exact-match redirect URI, 48 hours green staging, and Swiggy approval.",
      artifacts: [
        artifact("traffic_readiness"),
        artifact("backpressure_governor"),
        artifact("load_lab"),
        artifact("offer_intelligence"),
        artifact("order_lifecycle"),
        artifact("slo_incident_command"),
        artifact("data_governance"),
        artifact("enterprise_delegated_auth"),
        artifact("route_optimizer"),
        artifact("resilience"),
        artifact("trace_monitor"),
        artifact("audit_ledger"),
      ],
    },
  ];
}

function subjectFor(config: ServerConfig) {
  return `MealPilot India - Swiggy Builders Club access review (${config.swiggyMode})`;
}

function readinessLabelFor(config: ServerConfig): LaunchBundle["readinessLabel"] {
  if (config.swiggyMode === "production" && hasClientId(config) && config.swiggyRedirectUri.startsWith("https://")) {
    return "production_ready";
  }

  if (hasClientId(config)) return "staging_ready";

  return "local_review_ready";
}

export function buildLaunchBundle(options: { config: ServerConfig; latestPlan?: MealPlan }): LaunchBundle {
  const artifacts = buildArtifacts(options.latestPlan);
  const phases = buildPhases(options.config, options.latestPlan, artifacts);
  const accessApplication = [
    { label: "Integration name & organization", value: "MealPilot India / Farhan Khan", status: "ready" as const },
    { label: "Redirect URIs", value: options.config.swiggyRedirectUri, status: options.config.swiggyRedirectUri.startsWith("https://") ? "ready" as const : "manual_input" as const },
    { label: "Servers", value: requestedServers.join(", "), status: "ready" as const },
    {
      label: "Expected volume",
      value: "200 pilot sessions/day, about 2,400 tool calls/day, below 1 peak QPS; details in /api/traffic-readiness-plan",
      status: "ready" as const,
    },
    {
      label: "Use case",
      value: "Premium AI meal operating system across Food, Instamart, and Dineout with explicit confirmations.",
      status: "ready" as const,
    },
    { label: "Primary technical contact", value: "Add final engineering email before submission", status: "manual_input" as const },
    { label: "Demo video", value: "Record final localhost or staging run and attach URL", status: "manual_input" as const },
  ];
  const goLiveGates = [
    {
      label: "All 35 tools mapped and probed",
      status: "ready" as const,
      evidence: "/api/mcp/catalog and /api/mcp/tool-lab cover Food, Instamart, and Dineout.",
    },
    {
      label: "OAuth and DCR evidence",
      status: "ready" as const,
      evidence: "/api/credential-onboarding previews DCR; /api/auth/swiggy/status proves PKCE, callback, and token posture.",
    },
    {
      label: "Runtime logging and tracing",
      status: "ready" as const,
      evidence: "/api/telemetry/runtime, /api/audit-ledger, and /api/observability/traces expose redacted support-ready evidence.",
    },
    {
      label: "Traffic and capacity profile",
      status: "ready" as const,
      evidence: "/api/traffic-readiness-plan maps expected volume, QPS, Retry-After handling, major-event notice, and staged rollout.",
    },
    {
      label: "SLO and incident command",
      status: "ready" as const,
      evidence: "/api/slo-incident-command maps uptime, latency, status-page fallback, maintenance windows, and escalation evidence.",
    },
    {
      label: "Data governance and DSR posture",
      status: "ready" as const,
      evidence: "/api/data-governance-center maps DPDP roles, PII flows, local DSR endpoints, Swiggy DSR routing, retention, and token redaction.",
    },
    {
      label: "Enterprise delegated-auth readiness",
      status: "external_gate" as const,
      evidence:
        "/api/enterprise-delegated-auth proves the OBO flow design; platform-operator approval, final redirect allowlist, and partner contract remain external.",
    },
    {
      label: "Staging green for 48 hours",
      status: "external_gate" as const,
      evidence: "Requires Swiggy-issued staging credentials, seeded-data verification, and /api/staging-certification-matrix soak evidence.",
    },
    {
      label: "Production credentials",
      status: "external_gate" as const,
      evidence: "Requires Swiggy Builder Access approval after staging.",
    },
  ];
  const scoreItems = [...artifacts.map((item) => item.status), ...phases.map((phase) => phase.status), ...goLiveGates.map((gate) => gate.status)];
  const score = Math.round((scoreItems.reduce((sum, status) => sum + statusScore(status), 0) / scoreItems.length) * 100);
  const body = [
    "Hi Swiggy Builders team,",
    "",
    "Sharing MealPilot India for Builder Access review. It is a premium AI meal-planning and commerce assistant using Food, Instamart, and Dineout with explicit confirmation gates.",
    "",
    "Key proof links:",
    "- Builder packet: /api/builder-package.md",
    "- Executable packet export: /api/builder-packet-export",
    "- Packet Markdown export: /api/builder-packet-export.md",
    "- Website Atlas: /api/swiggy-website-atlas",
    "- Swiggy Builders Module Intelligence Center: /api/swiggy-builders-module-intelligence",
    "- Swiggy Builders Journey Gate Center: /api/swiggy-builders-journey-gates",
    "- Swiggy Builders Homepage Experience Center: /api/swiggy-builders-homepage-experience",
    "- Swiggy Builders Source Evolution Center: /api/swiggy-builders-source-evolution",
    "- Swiggy Builders Live Source Resilience Center: /api/swiggy-builders-live-source-resilience",
    "- Swiggy Builders Launch Story Center: /api/swiggy-builders-launch-story",
    "- Deep Site Map: /api/swiggy-deep-site-map",
    "- Developer Quickstart Workbench: /api/swiggy-developer-quickstart",
    "- CTA Execution Center: /api/swiggy-cta-execution-center",
    "- Builder Intake Command Center: /api/swiggy-builder-intake",
    "- FAQ & Policy Center: /api/swiggy-faq-policy",
    "- Swiggy FAQ Resolution Center: /api/swiggy-faq-resolution-center",
    "- Growth Partnership Center: /api/swiggy-growth-partnership",
    "- Swiggy Builder Talent Signal Center: /api/swiggy-talent-signal-center",
    "- Swiggy Builders Conversion Center: /api/swiggy-conversion-center",
    "- Swiggy Benefits Activation Center: /api/swiggy-benefits-activation-center",
    "- Channel & Multimodal Studio: /api/channel-multimodal-studio",
    "- Swiggy Visual Dish Capture Center: /api/swiggy-visual-dish-capture",
    "- Swiggy Voice Commerce Rehearsal Center: /api/swiggy-voice-commerce-center",
    "- Swiggy Quality Loop Center: /api/swiggy-quality-loop-center",
    "- Swiggy Ritual Autopilot Center: /api/swiggy-ritual-autopilot-center",
    "- Swiggy Payment Truth Center: /api/swiggy-payment-truth-center",
    "- Swiggy Meal Window Intelligence: /api/swiggy-meal-window-intelligence",
    "- Swiggy Customization Studio: /api/swiggy-customization-studio",
    "- Nutrition & Budget Intelligence: /api/nutrition-budget-intelligence",
    "- Household Preference Graph: /api/household-preference-graph",
    "- Guest Collaboration & Calendar Center: /api/guest-collaboration-calendar",
    "- Luxury Experience Workspace: /api/luxury-experience-workspace",
    "- Reviewer Artifact Vault: /api/reviewer-artifact-vault",
    "- Swiggy Builders Review Decision Center: /api/swiggy-builders-review-decision",
    "- Swiggy Demo Evidence Director: /api/swiggy-demo-evidence-director",
    "- Swiggy Showcase Submission Center: /api/swiggy-showcase-submission-center",
    "- Swiggy Partner Support Room: /api/swiggy-partner-support-room",
    "- Swiggy Access Evidence Matrix: /api/swiggy-access-evidence-matrix",
    "- Visual QA Center: /api/visual-qa-center",
    "- Submission Console: /api/submission-console",
    "- Access Submission Studio: /api/access-submission-studio",
    "- Swiggy Submission Timeline Center: /api/swiggy-submission-timeline-center",
    "- Swiggy Partner Success Desk: /api/swiggy-partner-success-desk",
    "- Swiggy Builders Site Parity: /api/swiggy-builders-site-parity",
    "- Swiggy Builders Page Mesh: /api/swiggy-builders-page-mesh",
    "- CTA Live Audit: /api/swiggy-cta-live-audit",
    "- Swiggy Interaction QA Center: /api/swiggy-interaction-qa-center",
    "- Swiggy Source Freeze Diff: /api/swiggy-source-freeze-diff",
    "- Access Submission Rehearsal: /api/access-submission-studio/rehearse",
    "- Reviewer Artifact Packet Composer: /api/reviewer-artifact-vault/compose",
    "- Visual QA Rehearsal: /api/visual-qa-center/rehearse",
    "- Docs Coverage Drill: /api/swiggy-docs-coverage/drill",
    "- Docs Twin Rehearsal: /api/swiggy-docs-twin-explorer/rehearse",
    "- llms Manifest Rehearsal: /api/swiggy-llms-manifest-verifier/rehearse",
    "- AI Client Config Validation: /api/ai-client-connect-kit/validate-config",
    "- Brand Compliance Rehearsal: /api/brand-compliance-kit/rehearse",
    "- Interaction QA Rehearsal: /api/swiggy-interaction-qa-center/rehearse",
    "- Source Freeze Rehearsal: /api/swiggy-source-freeze-diff/freeze",
    "- Growth Partnership Composer: /api/swiggy-growth-partnership/compose",
    "- Partner Success Composer: /api/swiggy-partner-success-desk/compose",
    "- Showcase Submission Composer: /api/swiggy-showcase-submission-center/compose",
    "- Channel & Multimodal Composer: /api/channel-multimodal-studio/compose",
    "- Nutrition & Budget Advisor: /api/nutrition-budget-intelligence/advise",
    "- Household Preference Simulator: /api/household-preference-graph/simulate",
    "- Guest Collaboration Composer: /api/guest-collaboration-calendar/compose",
    "- Luxury Experience Composer: /api/luxury-experience-workspace/compose",
    "- Swiggy Docs Coverage: /api/swiggy-docs-coverage",
    "- Swiggy Docs Twin Explorer: /api/swiggy-docs-twin-explorer",
    "- Swiggy Upstream Watch: /api/swiggy-upstream-watch",
    "- Swiggy Source Intelligence: /api/swiggy-source-intelligence",
    "- Swiggy Innovation Radar: /api/swiggy-innovation-radar",
    "- AI Client Connect Kit: /api/ai-client-connect-kit",
    "- Coding Agent Governance: /api/coding-agent-governance",
    "- MCP Gateway: /api/mcp-gateway",
    "- Swiggy Handshake Doctor: /api/mcp/handshake-doctor",
    "- Swiggy llms Manifest Verifier: /api/swiggy-llms-manifest-verifier",
    "- Swiggy Tool Parity Auditor: /api/swiggy-tool-parity-auditor",
    "- Swiggy Journey Compiler: /api/swiggy-journey-compiler",
    "- Swiggy Access Dossier: /api/swiggy-access-dossier",
    "- Premium Use Case Studio: /api/premium-use-case-studio",
    "- Premium Concierge Itinerary: /api/premium-concierge-itinerary",
    "- Staging Certification Matrix: /api/staging-certification-matrix",
    "- Brand Compliance Kit: /api/brand-compliance-kit",
    "- Tool Contract Matrix: /api/mcp/tool-contract-matrix",
    "- Scenario Runner: /api/mcp/scenario-runner",
    "- State Orchestrator: /api/mcp/state-orchestrator",
    "- Widget Runtime Center: /api/mcp/widget-runtime",
    "- Swiggy Widget Experience Composer: /api/swiggy-widget-experience-composer",
    "- Swiggy Hosted Widget Activation Center: /api/swiggy-hosted-widget-activation",
    "- Swiggy Agent Experience Benchmark: /api/swiggy-agent-experience-benchmark",
    "- Swiggy Private Pilot Control Room: /api/swiggy-private-pilot-control-room",
    "- Swiggy Staging Replay Center: /api/swiggy-staging-replay",
    "- Commercial Action Guard: /api/mcp/commercial-action-guard",
    "- Staging Cutover Rehearsal: /api/mcp/staging-cutover",
    "- Swiggy Staging Credential Drill Center: /api/swiggy-staging-credential-drill",
    "- Swiggy Credential Vault Center: /api/swiggy-credential-vault-center",
    "- Swiggy Staging Seed & Smoke Center: /api/swiggy-staging-seed-smoke-center",
    "- Swiggy Credential Handoff Center: /api/swiggy-credential-handoff-center",
    "- Swiggy Credential Readiness Dossier: /api/swiggy-credential-readiness-dossier",
    "- Credential Issuance Receipt State: /api/swiggy-credential-issuance/state",
    "- Health Check: /api/health",
    "- Readiness Check: /api/ready",
    "- Runtime Config: /api/config",
    "- Privacy Delete: /api/privacy",
    "- Privacy Export: /api/privacy/export",
    "- Storage Status: /api/storage/status",
    "- Storage Export: /api/storage/export",
    "- Storage Compact: /api/storage/compact",
    "- Storage Restore: /api/storage/restore",
    "- Reviewer Proof: /api/reviewer-proof",
    "- Evaluation Lab: /api/evaluation-lab",
    "- Submission Package: /api/submission-package",
    "- Demo Studio: /api/demo-studio",
    "- Support Bridge Report: /api/support/bridge/report",
    "- Session Readback: /api/sessions/{sessionId}",
    "- Session Preflight: /api/sessions/{sessionId}/preflight",
    "- Session Replay: /api/sessions/{sessionId}/replay",
    "- Session Widgets: /api/sessions/{sessionId}/widgets",
    "- Session Staging Transcript: /api/sessions/{sessionId}/staging-transcript",
    "- Planner API: /api/plan",
    "- Confirmation API: /api/confirm",
    "- Confirm All API: /api/confirm-all",
    "- Go Live Checklist: /api/go-live",
    "- Swiggy Live Signal Calibration Center: /api/swiggy-live-signal-calibration",
    "- Data Governance Center: /api/data-governance-center",
    "- Enterprise Delegated Auth Center: /api/enterprise-delegated-auth",
    "- Traffic Readiness Plan: /api/traffic-readiness-plan",
    "- MCP Backpressure Governor: /api/mcp/backpressure-governor",
    "- Swiggy Load Lab: /api/swiggy-load-lab",
    "- Swiggy Quota Negotiation Center: /api/swiggy-quota-negotiation-center",
    "- Swiggy Operating Contract Center: /api/swiggy-operating-contract-center",
    "- Swiggy Offer Intelligence: /api/swiggy-offer-intelligence",
    "- Swiggy Order Lifecycle: /api/swiggy-order-lifecycle",
    "- Swiggy Location Trust: /api/swiggy-location-trust",
    "- Swiggy Cart Mutation Workbench: /api/swiggy-cart-mutation-workbench",
    "- Swiggy Discovery Freshness: /api/swiggy-discovery-freshness",
    "- Swiggy Confirmation Command Center: /api/swiggy-confirmation-command-center",
    "- Swiggy Cancellation & Care Center: /api/swiggy-cancellation-care-center",
    "- Swiggy Dineout Precision Center: /api/swiggy-dineout-precision-center",
    "- SLO Incident Command Center: /api/slo-incident-command",
    "- MCP Tool Lab: /api/mcp/tool-lab",
    "- MCP Capability Registry: /api/mcp/capability-registry",
    "- Resource & Prompt Studio: /api/mcp/resource-prompt-studio",
    "- Credential Cockpit: /api/credential-onboarding",
    "- Credential Handoff Center: /api/swiggy-credential-handoff-center",
    "- Credential Readiness Dossier: /api/swiggy-credential-readiness-dossier",
    "- Credential Issuance Receipt State: /api/swiggy-credential-issuance/state",
    "- Sandbox Credential Workbench: /api/sandbox-credential-workbench",
    "- Swiggy OAuth Status: /api/auth/swiggy/status",
    "- Swiggy Auth Lifecycle Center: /api/swiggy-auth-lifecycle-center",
    "- Swiggy Enterprise Platform Center: /api/enterprise-platform-center",
    "- Error Intelligence: /api/error-intelligence",
    "- Support Bridge: /api/support/bridge",
    "- Runtime Telemetry: /api/telemetry/runtime",
    "- Audit Ledger Center: /api/audit-ledger",
    options.latestPlan
      ? `- Staging Transcript Export: /api/sessions/${options.latestPlan.id}/staging-transcript`
      : "- Staging Transcript Export: run one plan to generate session-scoped evidence",
    "- Production smoke: npm run verify:production",
    "",
    "Manual attachments before submission: demo video URL, final technical contact email, final HTTPS redirect URI.",
  ].join("\n");

  return {
    generatedAt: new Date().toISOString(),
    score,
    readinessLabel: readinessLabelFor(options.config),
    integrationName: "MealPilot India",
    requestedServers,
    reviewerNarrative:
      "MealPilot is a confirmation-first Swiggy MCP product that composes delivery, groceries, and table reservations into one household meal operating system with complete local proof, telemetry, and review artifacts.",
    artifacts,
    phases,
    commands: [
      { id: "install", command: "npm install", proves: "Dependencies resolve for local reviewer setup." },
      { id: "dev", command: "npm run dev", proves: "Runs API and web app for localhost demo." },
      { id: "quality", command: "npm test && npm run lint && npm run build", proves: "Tests, lint, and production build pass." },
      { id: "smoke", command: "npm start && npm run verify:production", proves: "Production-style server exposes all reviewer proof endpoints." },
    ],
    accessApplication,
    goLiveGates,
    handoffEmail: {
      to: "builders@swiggy.in",
      subject: subjectFor(options.config),
      body,
    },
  };
}
