import type {
  PremiumUseCaseBlueprint,
  PremiumUseCaseRouteStep,
  PremiumUseCaseStage,
  PremiumUseCaseStudio,
  PremiumUseCaseSurface,
  PremiumUseCaseTier,
  SwiggyServer,
} from "../../src/domain/types.js";
import { buildMcpCoverage } from "./advancedWorkflows.js";

const officialSources = [
  "https://mcp.swiggy.com/builders/",
  "https://mcp.swiggy.com/builders/docs/start/what-is-swiggy-mcp/",
  "https://mcp.swiggy.com/builders/docs/build/",
  "https://mcp.swiggy.com/builders/docs/build/agent-patterns/voice-vs-chat/",
  "https://mcp.swiggy.com/builders/docs/build/agent-patterns/multi-turn-state/",
  "https://mcp.swiggy.com/builders/docs/build/widgets/",
  "https://mcp.swiggy.com/builders/docs/operate/rate-limits/",
];

function routeStep(
  sequence: number,
  label: string,
  servers: SwiggyServer[],
  tools: string[],
  purpose: string,
  optimization: string,
  confirmationGate: string,
  surface: PremiumUseCaseSurface,
): PremiumUseCaseRouteStep {
  return { sequence, label, servers, tools, purpose, optimization, confirmationGate, surface };
}

function useCase(
  id: string,
  title: string,
  tier: PremiumUseCaseTier,
  stage: PremiumUseCaseStage,
  audience: string,
  promise: string,
  baselineCalls: number,
  optimizedCalls: number,
  route: PremiumUseCaseRouteStep[],
  safetyGates: string[],
  dataBoundaries: string[],
  successMetrics: string[],
  premiumDifferentiators: string[],
): PremiumUseCaseBlueprint {
  const servers = [...new Set(route.flatMap((step) => step.servers))];
  const primaryTools = [...new Set(route.flatMap((step) => step.tools))];
  return {
    id,
    title,
    tier,
    stage,
    audience,
    promise,
    servers,
    primaryTools,
    baselineCalls,
    optimizedCalls,
    savedCalls: baselineCalls - optimizedCalls,
    route,
    safetyGates,
    dataBoundaries,
    successMetrics,
    premiumDifferentiators,
  };
}

const useCases: PremiumUseCaseBlueprint[] = [
  useCase(
    "household_week_reset",
    "Household Week Reset",
    "signature",
    "demo_ready",
    "Families and busy professionals planning the week in one high-trust flow.",
    "Turn one budget, diet, and schedule prompt into meals, pantry replenishment, and one social dining option.",
    29,
    18,
    [
      routeStep(
        1,
        "Resolve commerce state once",
        ["food", "instamart", "dineout"],
        ["food.get_addresses", "instamart.get_addresses", "dineout.get_saved_locations"],
        "Anchor Food, grocery, and dining suggestions to the user's saved places.",
        "Share resolved location context across planner lanes while respecting different address and lat/lng scopes.",
        "No commercial action.",
        "chat",
      ),
      routeStep(
        2,
        "Build weekly options",
        ["food", "instamart", "dineout"],
        [
          "food.search_restaurants",
          "food.get_restaurant_menu",
          "food.search_menu",
          "instamart.search_products",
          "dineout.search_restaurants_dineout",
          "dineout.get_restaurant_details",
        ],
        "Create delivery, cook-at-home, and Dineout choices in one comparison.",
        "Parallelize Food menu reads with Instamart product search after location resolution.",
        "Surface distance, availability, allergy, and budget tradeoffs before cart mutations.",
        "widget",
      ),
      routeStep(
        3,
        "Prepare carts and offers",
        ["food", "instamart"],
        [
          "food.update_food_cart",
          "food.fetch_food_coupons",
          "food.apply_food_coupon",
          "food.get_food_cart",
          "instamart.update_cart",
          "instamart.get_cart",
        ],
        "Prepare the chosen meal and pantry basket without placing orders.",
        "Read carts before confirmation; apply COD-compatible Food offers only.",
        "Confirm item list, substitutions, cart total, COD, and delivery ETA.",
        "chat",
      ),
      routeStep(
        4,
        "Confirm and monitor",
        ["food", "instamart", "dineout"],
        [
          "food.place_food_order",
          "food.track_food_order",
          "instamart.checkout",
          "instamart.track_order",
          "dineout.get_available_slots",
          "dineout.create_cart",
          "dineout.book_table",
          "dineout.get_booking_status",
        ],
        "Execute only user-approved order, checkout, and booking decisions.",
        "Gate non-idempotent calls and use tracking/status reads after placement.",
        "Separate confirmations for Food, Instamart, and Dineout.",
        "ops",
      ),
    ],
    [
      "No hidden checkout behind a generic continue button.",
      "Food order cap and COD are repeated before place_food_order.",
      "Instamart cart is read before checkout.",
      "Dineout slot, guest count, and free booking status are confirmed before book_table.",
    ],
    [
      "No raw addresses in voice or cards.",
      "No payment details stored.",
      "Swiggy-originated data is used only for the current planning session.",
    ],
    ["Weekly plan completion", "Cart-to-confirmation conversion", "Saved calls per plan", "Manual edits avoided"],
    [
      "Three-server household operating system, not a single order bot.",
      "Budget-aware tradeoff view across delivery, cooking, and going out.",
      "Proof-ready audit trail for every commercial action.",
    ],
  ),
  useCase(
    "voice_fridge_to_dinner",
    "Voice Fridge-To-Dinner Concierge",
    "concierge",
    "demo_ready",
    "Hands-busy households using a car, speaker, or ambient assistant before dinner.",
    "Use voice to choose between reordering staples, cooking with current pantry, or ordering a quick meal.",
    17,
    10,
    [
      routeStep(
        1,
        "Voice-safe inventory prompt",
        ["instamart"],
        ["instamart.get_addresses", "instamart.your_go_to_items", "instamart.search_products"],
        "Find likely staples and one-tap reorder candidates.",
        "Prefer your_go_to_items over broad search when the user is on voice.",
        "No purchase without spoken confirmation.",
        "voice",
      ),
      routeStep(
        2,
        "Fallback dinner search",
        ["food"],
        ["food.get_addresses", "food.search_restaurants", "food.search_menu"],
        "Offer up to three food options if the user does not want to cook.",
        "Compress results to the top three and avoid raw IDs.",
        "Read total and ETA aloud before cart mutation and placement.",
        "voice",
      ),
      routeStep(
        3,
        "Minimal checkout path",
        ["instamart", "food"],
        [
          "instamart.update_cart",
          "instamart.get_cart",
          "instamart.checkout",
          "food.update_food_cart",
          "food.get_food_cart",
          "food.place_food_order",
        ],
        "Execute only the chosen path after explicit user approval.",
        "Do not run both Food placement and Instamart checkout unless the user asks for both.",
        "Spoken confirmation with cart total, ETA, and COD/payment scope.",
        "voice",
      ),
    ],
    [
      "Maximum three spoken options.",
      "Never read addressId, restaurantId, itemId, or spinId.",
      "Confirm before cart-changing and commercial calls.",
    ],
    ["Voice transcript redacts IDs.", "No raw tokens or full addresses leave the server."],
    ["Time to dinner decision", "Voice confirmation accuracy", "Fallback rate from Instamart to Food"],
    [
      "Luxury voice flow that feels like a kitchen concierge.",
      "Uses Swiggy's surface-specific response contract instead of reading long lists aloud.",
    ],
  ),
  useCase(
    "date_night_orchestrator",
    "Date Night Orchestrator",
    "signature",
    "demo_ready",
    "Couples planning a restaurant evening plus dessert or breakfast-at-home follow-up.",
    "Book the table first, then prepare a later dessert reminder or next-morning Instamart basket.",
    21,
    13,
    [
      routeStep(
        1,
        "Find the reservation",
        ["dineout"],
        [
          "dineout.get_saved_locations",
          "dineout.search_restaurants_dineout",
          "dineout.get_restaurant_details",
          "dineout.get_available_slots",
        ],
        "Find Dineout venues with available slots and date-night amenities.",
        "Use Dineout lat/lng directly and filter unavailable restaurants before presentation.",
        "Confirm date, time, party size, and restaurant.",
        "widget",
      ),
      routeStep(
        2,
        "Reserve safely",
        ["dineout"],
        ["dineout.create_cart", "dineout.book_table", "dineout.get_booking_status"],
        "Create the free booking and read the status back.",
        "Use get_booking_status before retrying if book_table times out.",
        "book_table needs explicit slot confirmation.",
        "chat",
      ),
      routeStep(
        3,
        "Plan after-dinner comfort",
        ["food", "instamart"],
        [
          "food.get_addresses",
          "food.search_restaurants",
          "food.get_restaurant_menu",
          "food.update_food_cart",
          "food.get_food_cart",
          "instamart.search_products",
          "instamart.update_cart",
          "instamart.get_cart",
        ],
        "Prepare dessert delivery or breakfast staples as a reminder/place-later flow.",
        "Avoid future Food scheduling; store reminder and call placement later.",
        "Separate order and grocery confirmations.",
        "chat",
      ),
    ],
    ["Dineout booking first.", "Future Food delivery is reminder-based until Swiggy supports scheduling.", "No paid Dineout booking assumed."],
    ["Restaurant details shown without exposing internal IDs.", "Reminder stores only minimal intent."],
    ["Reservation completion", "Reminder follow-through", "Restaurant fit rating"],
    ["Turns a one-off table booking into an end-to-end evening assistant.", "Handles Swiggy's different location models explicitly."],
  ),
  useCase(
    "office_lunch_boardroom",
    "Office Lunch Boardroom",
    "enterprise",
    "enterprise_extension",
    "Small offices ordering team lunch with snacks and a future enterprise delegated-auth path.",
    "Collect group constraints, produce an allergy-safe Food order, and add Instamart beverages or snacks.",
    26,
    16,
    [
      routeStep(
        1,
        "Resolve office delivery",
        ["food", "instamart"],
        ["food.get_addresses", "instamart.get_addresses", "instamart.create_address"],
        "Use an office address or create one when the user has no saved office location.",
        "Only create_address after the user confirms the address text.",
        "Address creation requires explicit confirmation.",
        "chat",
      ),
      routeStep(
        2,
        "Group-friendly discovery",
        ["food", "instamart"],
        [
          "food.search_restaurants",
          "food.get_restaurant_menu",
          "food.search_menu",
          "instamart.search_products",
          "instamart.your_go_to_items",
        ],
        "Find shared mains, individual bowls, drinks, and snack add-ons.",
        "Use search_menu for dietary keywords instead of repeatedly reading full menus.",
        "Show allergy and budget labels before cart changes.",
        "widget",
      ),
      routeStep(
        3,
        "Commercial split",
        ["food", "instamart"],
        [
          "food.update_food_cart",
          "food.fetch_food_coupons",
          "food.apply_food_coupon",
          "food.get_food_cart",
          "food.place_food_order",
          "instamart.update_cart",
          "instamart.get_cart",
          "instamart.checkout",
        ],
        "Prepare and execute the approved lunch and snack baskets.",
        "Keep Food and Instamart carts independent with separate confirmations.",
        "Confirm per-server total, ETA, and recipients.",
        "ops",
      ),
    ],
    ["One confirmation per commercial action.", "Allergy constraints displayed before placement.", "Enterprise delegated auth remains external."],
    ["No employee dietary data stored beyond the session by default.", "Office address creation is user-approved."],
    ["Per-person budget fit", "Allergy-safe coverage", "Average calls per participant"],
    ["Boardroom-grade group ordering with snacks and lunch in one plan.", "Natural enterprise lane for delegated auth and higher rate limits."],
  ),
  useCase(
    "care_circle_meals",
    "Care Circle Meals",
    "concierge",
    "demo_ready",
    "Families coordinating meals and groceries for older parents or recovering relatives.",
    "Prepare gentle meals, staples, and tracking updates with support-ready recovery if anything fails.",
    24,
    15,
    [
      routeStep(
        1,
        "Preference-sensitive discovery",
        ["food", "instamart"],
        [
          "food.get_addresses",
          "food.search_restaurants",
          "food.get_restaurant_menu",
          "instamart.get_addresses",
          "instamart.search_products",
          "instamart.your_go_to_items",
        ],
        "Find low-spice food and recurring household staples.",
        "Cache preferences locally, but always read current Swiggy availability.",
        "No commercial action.",
        "chat",
      ),
      routeStep(
        2,
        "Confirm gentle basket",
        ["food", "instamart"],
        [
          "food.update_food_cart",
          "food.get_food_cart",
          "food.place_food_order",
          "instamart.update_cart",
          "instamart.get_cart",
          "instamart.checkout",
        ],
        "Place only user-approved meals or grocery essentials.",
        "Require confirmation from the account holder or authorized caregiver.",
        "Confirm recipient, total, ETA, and substitutions.",
        "chat",
      ),
      routeStep(
        3,
        "Care tracking and support",
        ["food", "instamart"],
        [
          "food.get_food_orders",
          "food.get_food_order_details",
          "food.track_food_order",
          "food.report_error",
          "instamart.get_orders",
          "instamart.get_order_details",
          "instamart.track_order",
          "instamart.report_error",
        ],
        "Give family-safe tracking updates and report failures with redacted context.",
        "Use status/detail tools before report_error to avoid vague support tickets.",
        "Support report requires user-visible error summary.",
        "ops",
      ),
    ],
    ["Authorized user confirmation.", "No blind retry after commercial calls.", "Escalate with report_error only after status reads."],
    ["Health preferences are user-provided and editable.", "No diagnosis or medical claim is inferred."],
    ["Successful delivery tracking", "Support resolution time", "Caregiver confidence score"],
    ["Premium family-care use case with tracking and support baked in.", "Uses order detail tools as a trust layer, not just placement."],
  ),
  useCase(
    "pantry_autopilot_plus",
    "Pantry Autopilot Plus",
    "signature",
    "demo_ready",
    "Urban homes that want groceries maintained without noisy weekly list making.",
    "Detect likely pantry gaps, suggest Instamart replenishment, and add Food fallback when cooking is not viable.",
    20,
    12,
    [
      routeStep(
        1,
        "Read go-to grocery state",
        ["instamart"],
        ["instamart.get_addresses", "instamart.your_go_to_items", "instamart.search_products"],
        "Infer replenishment candidates from frequent items and explicit pantry targets.",
        "Use go-to items first, then search only missing categories.",
        "No checkout without cart confirmation.",
        "widget",
      ),
      routeStep(
        2,
        "Maintain cart safely",
        ["instamart"],
        [
          "instamart.update_cart",
          "instamart.get_cart",
          "instamart.clear_cart",
          "instamart.checkout",
          "instamart.get_orders",
          "instamart.track_order",
        ],
        "Build, clear, or checkout the grocery basket depending on serviceability and address changes.",
        "Clear cart before address switch to avoid stock/serviceability mismatch.",
        "Confirm total, substitutions, and minimum order.",
        "chat",
      ),
      routeStep(
        3,
        "Food fallback",
        ["food"],
        ["food.search_restaurants", "food.search_menu", "food.update_food_cart", "food.get_food_cart"],
        "Prepare a quick Food fallback if pantry items are unavailable.",
        "Do not place fallback order without a separate Food confirmation.",
        "Separate fallback confirmation.",
        "chat",
      ),
    ],
    ["Cart truth read before checkout.", "Address switch clears or rebuilds cart.", "Food fallback never auto-places."],
    ["Pantry targets are local preferences.", "Order history is read only when the user asks for reorder context."],
    ["Pantry fill rate", "Cart rebuild rate", "Out-of-stock recovery"],
    ["Feels like a private household supply manager.", "Uses Instamart's reorder affordance as the main path, not endless search."],
  ),
  useCase(
    "rainy_day_rescue",
    "Rainy-Day Rescue",
    "concierge",
    "demo_ready",
    "Users facing weather, delays, or a failed cart during a high-friction meal moment.",
    "Recover from closed restaurants, expired carts, unavailable products, and support incidents without losing the user's plan.",
    23,
    14,
    [
      routeStep(
        1,
        "Detect the failure",
        ["food", "instamart"],
        [
          "food.get_food_cart",
          "food.flush_food_cart",
          "food.search_restaurants",
          "instamart.get_cart",
          "instamart.clear_cart",
          "instamart.search_products",
        ],
        "Understand whether Food cart, Instamart cart, restaurant, or stock state changed.",
        "Read cart before clearing; rebuild only with user consent.",
        "Warn before clearing any cart.",
        "chat",
      ),
      routeStep(
        2,
        "Recover with alternatives",
        ["food", "instamart", "dineout"],
        [
          "food.search_menu",
          "food.get_restaurant_menu",
          "instamart.update_cart",
          "instamart.get_cart",
          "dineout.search_restaurants_dineout",
          "dineout.get_available_slots",
        ],
        "Offer alternative dishes, grocery substitutions, or nearby Dineout slots.",
        "Use the cheapest safe branch first, then escalate to a cross-server option.",
        "Confirmation before each branch mutation.",
        "widget",
      ),
      routeStep(
        3,
        "Escalate if needed",
        ["food", "instamart", "dineout"],
        ["food.report_error", "instamart.report_error", "dineout.report_error"],
        "Generate Swiggy-ready support payloads if user wants to report the issue.",
        "Attach session id and redacted tool context.",
        "User approves report summary.",
        "ops",
      ),
    ],
    ["No blind retry.", "Clear cart only after warning.", "Report errors only with user-visible context."],
    ["Only redacted support context is retained.", "No competitor benchmarking during recovery."],
    ["Recovered plan rate", "Cart loss avoided", "Support report completion"],
    ["Turns failures into a premium rescue flow instead of an apology screen.", "Uses all three report_error tools as a real support bridge."],
  ),
  useCase(
    "guest_hosting_os",
    "Guest Hosting OS",
    "signature",
    "demo_ready",
    "Hosts coordinating dinner, snacks, drinks, and backup reservations for guests.",
    "Plan a home gathering with Instamart supplies, Food backup, and Dineout contingency.",
    31,
    19,
    [
      routeStep(
        1,
        "Plan supplies and backup",
        ["instamart", "food", "dineout"],
        [
          "instamart.get_addresses",
          "instamart.search_products",
          "food.get_addresses",
          "food.search_restaurants",
          "dineout.get_saved_locations",
          "dineout.search_restaurants_dineout",
        ],
        "Create a host plan across home supplies, delivery backup, and nearby reservation fallback.",
        "Parallelize the three search lanes after resolving locations.",
        "No commercial action.",
        "widget",
      ),
      routeStep(
        2,
        "Prepare the host basket",
        ["instamart", "food"],
        [
          "instamart.update_cart",
          "instamart.get_cart",
          "food.get_restaurant_menu",
          "food.update_food_cart",
          "food.fetch_food_coupons",
          "food.apply_food_coupon",
          "food.get_food_cart",
        ],
        "Prepare supplies and a backup food cart.",
        "Delay Food placement unless the host switches from cook-at-home to delivery.",
        "Separate host basket and food backup confirmation.",
        "chat",
      ),
      routeStep(
        3,
        "Execute contingency",
        ["instamart", "food", "dineout"],
        [
          "instamart.checkout",
          "instamart.track_order",
          "food.place_food_order",
          "food.track_food_order",
          "dineout.get_restaurant_details",
          "dineout.get_available_slots",
          "dineout.book_table",
          "dineout.get_booking_status",
        ],
        "Execute the chosen branch and monitor guest-impacting status.",
        "Use only one fallback branch unless the host confirms multiple actions.",
        "Confirm each commercial branch separately.",
        "ops",
      ),
    ],
    ["No automatic fallback placement.", "Dineout party size confirmed.", "Food and Instamart totals shown separately."],
    ["Guest preferences remain local group constraints.", "No full address in shared host view."],
    ["Host prep confidence", "Backup branch activation", "On-time arrival rate"],
    ["A premium home-hosting product nobody gets from a plain delivery agent.", "Combines Swiggy's three surfaces into one evening command center."],
  ),
  useCase(
    "traveler_hotel_mode",
    "Traveler Hotel Mode",
    "concierge",
    "staging_after_credentials",
    "Travelers staying in hotels or serviced apartments who need location-aware meals without address confusion.",
    "Use current city and saved locations to suggest delivery, convenience items, and Dineout options near the stay.",
    18,
    11,
    [
      routeStep(
        1,
        "Clarify temporary location",
        ["food", "instamart", "dineout"],
        [
          "food.get_addresses",
          "instamart.get_addresses",
          "instamart.create_address",
          "dineout.get_saved_locations",
        ],
        "Handle temporary stay address while keeping saved Home intact.",
        "Create a temporary address only after confirmation.",
        "Explicit address confirmation.",
        "chat",
      ),
      routeStep(
        2,
        "Choose hotel-friendly path",
        ["food", "instamart", "dineout"],
        [
          "food.search_restaurants",
          "food.get_restaurant_menu",
          "instamart.search_products",
          "dineout.search_restaurants_dineout",
          "dineout.get_restaurant_details",
        ],
        "Compare room delivery, essentials, and nearby going-out options.",
        "Favor low-call reads and show distance to avoid bad traveler surprises.",
        "No commercial action.",
        "widget",
      ),
      routeStep(
        3,
        "Clean up temporary data",
        ["instamart"],
        ["instamart.delete_address"],
        "Remove temporary address if the user asks after checkout or trip end.",
        "Do not delete saved addresses without explicit label confirmation.",
        "Address deletion requires confirmation.",
        "ops",
      ),
    ],
    ["Temporary address creation/deletion requires explicit confirmation.", "No assumptions about hotel delivery rules.", "Distance surfaced for far restaurants."],
    ["Temporary location is minimized and removable.", "No room number is exposed in shared proof artifacts."],
    ["Address confusion avoided", "Traveler repeat use", "Temporary data cleanup"],
    ["Solves a premium travel pain point with clear location scope.", "Makes Swiggy useful away from home without corrupting saved state."],
  ),
  useCase(
    "celebration_split_plan",
    "Celebration Split Plan",
    "signature",
    "demo_ready",
    "Users planning birthdays, anniversaries, or celebrations with restaurant, cake, snacks, and recovery support.",
    "Coordinate Dineout, Food dessert, and Instamart party supplies with explicit timing and branch decisions.",
    28,
    17,
    [
      routeStep(
        1,
        "Build celebration options",
        ["dineout", "food", "instamart"],
        [
          "dineout.get_saved_locations",
          "dineout.search_restaurants_dineout",
          "dineout.get_restaurant_details",
          "food.search_restaurants",
          "food.search_menu",
          "instamart.search_products",
        ],
        "Find celebration venue, dessert delivery, and party supplies.",
        "Use Dineout first for scarce slots, then Food/Instamart for flexible items.",
        "No commercial action.",
        "widget",
      ),
      routeStep(
        2,
        "Prepare timed actions",
        ["dineout", "food", "instamart"],
        [
          "dineout.get_available_slots",
          "dineout.create_cart",
          "food.get_restaurant_menu",
          "food.update_food_cart",
          "food.get_food_cart",
          "instamart.update_cart",
          "instamart.get_cart",
        ],
        "Prepare reservation, dessert cart, and supplies basket.",
        "Use reminders for later Food placement because scheduled Food delivery is not v1.",
        "Confirm slot, dessert cart, and supplies separately.",
        "chat",
      ),
      routeStep(
        3,
        "Confirm celebration",
        ["dineout", "food", "instamart"],
        [
          "dineout.book_table",
          "dineout.get_booking_status",
          "food.place_food_order",
          "food.get_food_orders",
          "instamart.checkout",
          "instamart.get_orders",
        ],
        "Execute only approved celebration actions and verify status after non-idempotent calls.",
        "Read order/booking status before retry if any commercial call returns 5xx.",
        "Separate confirmation per server.",
        "ops",
      ),
    ],
    ["No future Food delivery without reminder-based later placement.", "Status check before retry.", "Separate commercial confirmations."],
    ["Occasion notes are session-scoped unless user saves a reminder.", "No guest contact details required."],
    ["Celebration plan completeness", "Reminder accuracy", "Commercial retry safety"],
    ["Premium occasion planning, not mere ordering.", "Uses Swiggy's combined-agent strength for emotionally important events."],
  ),
  useCase(
    "swiggy_builder_reviewer_mode",
    "Swiggy Builder Reviewer Mode",
    "enterprise",
    "demo_ready",
    "Swiggy reviewers and internal operators evaluating MealPilot before access approval.",
    "Show every route, proof artifact, safety gate, and support payload without needing live credentials.",
    16,
    9,
    [
      routeStep(
        1,
        "Show route coverage",
        ["food", "instamart", "dineout"],
        [
          "food.get_food_order_details",
          "food.report_error",
          "instamart.get_order_details",
          "instamart.report_error",
          "dineout.get_booking_status",
          "dineout.report_error",
        ],
        "Demonstrate support-grade reads and report_error payloads in review mode.",
        "Use deterministic mock data until staging credentials exist.",
        "No commercial action in reviewer mode.",
        "ops",
      ),
      routeStep(
        2,
        "Validate every tool family",
        ["food", "instamart", "dineout"],
        [
          "food.get_addresses",
          "food.get_food_orders",
          "instamart.get_addresses",
          "instamart.get_orders",
          "dineout.get_saved_locations",
          "dineout.create_cart",
        ],
        "Prove coverage for location, order history, support, tracking, and Dineout cart primitives.",
        "Call local Tool Lab and Capability Registry before live traffic.",
        "Reviewer decides when to move to staging.",
        "ops",
      ),
    ],
    ["Mock review never places live orders.", "All external gates stay visible.", "Support report redacts raw PII."],
    ["Reviewer artifacts use seeded data.", "No Swiggy production calls without issued credentials."],
    ["Reviewer proof score", "Artifact completeness", "External gate clarity"],
    ["Turns the app itself into a Swiggy access-review console.", "Makes the demo operationally auditable, not just pretty."],
  ),
];

function toolKey(server: SwiggyServer, tool: string) {
  return `${server}.${tool}`;
}

function splitToolKey(key: string): { server: SwiggyServer; tool: string } | null {
  const [server, tool] = key.split(".");
  if (!tool || !["food", "instamart", "dineout"].includes(server)) return null;
  return { server: server as SwiggyServer, tool };
}

function isSplitToolKey(value: { server: SwiggyServer; tool: string } | null): value is { server: SwiggyServer; tool: string } {
  return value !== null;
}

export function buildPremiumUseCaseStudio(): PremiumUseCaseStudio {
  const coverage = buildMcpCoverage();
  const officialToolKeys = new Set(
    coverage.flatMap((server) => server.tools.map((tool) => toolKey(server.server, tool.tool))),
  );
  const usedToolKeys = new Set(useCases.flatMap((item) => item.route.flatMap((step) => step.tools)));
  const recognizedUsedToolKeys = [...usedToolKeys].filter((key) => officialToolKeys.has(key));
  const missingToolKeys = [...officialToolKeys].filter((key) => !usedToolKeys.has(key));
  const crossServerUseCases = useCases.filter((item) => item.servers.length > 1).length;
  const averageSavings =
    useCases.reduce((sum, item) => sum + item.savedCalls, 0) / Math.max(useCases.length, 1);
  const score = Math.min(100, Math.round(82 + crossServerUseCases * 1.4 + recognizedUsedToolKeys.length * 0.22));

  return {
    generatedAt: new Date().toISOString(),
    score,
    officialSources,
    totalUseCases: useCases.length,
    crossServerUseCases,
    totalToolsUsed: recognizedUsedToolKeys.length,
    totalOfficialTools: officialToolKeys.size,
    useCases,
    toolCoverage: coverage.map((server) => {
      const serverUsed = recognizedUsedToolKeys
        .map(splitToolKey)
        .filter(isSplitToolKey)
        .filter((tool) => tool.server === server.server);
      return {
        server: server.server,
        totalTools: server.totalTools,
        usedTools: new Set(serverUsed.map((item) => item.tool)).size,
        useCaseIds: useCases
          .filter((item) => item.route.some((step) => step.servers.includes(server.server)))
          .map((item) => item.id),
      };
    }),
    marketThesis: [
      "Swiggy MCP is strongest when an agent reasons across tools at runtime, so MealPilot should sell outcomes rather than single API calls.",
      "The premium moat is cross-server orchestration with explicit confirmation, support-grade observability, and surface-specific UX.",
      "Households, care circles, travel, celebrations, and office contexts create repeat use beyond one-off food ordering.",
      "Reviewer Mode makes the product easier for Swiggy to trust because capabilities, gaps, and external gates are inspectable.",
    ],
    innovationPrinciples: [
      "Resolve location once, then branch into Food, Instamart, and Dineout lanes without mixing their cart or order state.",
      "Read authoritative cart or status state at every turn boundary before mutating or retrying.",
      "Use voice for short curated choices, widgets for comparison, and ops surfaces for traces and support.",
      "Prefer reminder/place-later patterns where Swiggy v1 does not expose future scheduling.",
      "Treat report_error as a first-class support workflow, not an afterthought.",
    ],
    roadmap: [
      {
        phase: "Phase 1",
        title: "Signature household flows",
        deliverable: "Household Week Reset, Pantry Autopilot Plus, Guest Hosting OS, and Celebration Split Plan in mock/staging.",
        status: "demo_ready",
      },
      {
        phase: "Phase 2",
        title: "Surface excellence",
        deliverable: "Voice Fridge-To-Dinner, widget-backed comparison cards, and temporary Traveler Hotel Mode addresses after credentials.",
        status: "staging_after_credentials",
      },
      {
        phase: "Phase 3",
        title: "Support and care",
        deliverable: "Care Circle Meals and Rainy-Day Rescue with live support reports and order-detail verification.",
        status: "demo_ready",
      },
      {
        phase: "Phase 4",
        title: "Platform expansion",
        deliverable: "Office Lunch Boardroom and enterprise delegated-auth lane after Swiggy platform approval.",
        status: "enterprise_extension",
      },
    ],
    assertions: [
      `${recognizedUsedToolKeys.length}/${officialToolKeys.size} official Swiggy tools are placed into premium MealPilot use cases.`,
      `${crossServerUseCases}/${useCases.length} premium use cases use more than one Swiggy MCP server.`,
      `Average call savings per use case is ${averageSavings.toFixed(1)} calls through route planning, caching, and branch discipline.`,
      missingToolKeys.length === 0
        ? "No official Swiggy tool is left without a premium use-case home."
        : `Missing use-case tool coverage: ${missingToolKeys.join(", ")}.`,
      "Every use case keeps commercial actions behind explicit confirmation gates.",
    ],
    externalGates: [
      "Live staging credentials are required before real Food, Instamart, or Dineout traffic.",
      "Enterprise delegated auth is required before office or platform-scale multi-user brokerage.",
      "Swiggy widget iframe rendering remains gated until hosted widget responses are available.",
      "Future Food scheduled delivery remains a reminder/place-later product pattern until Swiggy exposes scheduling.",
    ],
  };
}
