import type { MealPlan, SupportBridgeReport, SupportBridgeToolReport, SwiggyServer } from "../../src/domain/types.js";

const servers: Array<{
  server: SwiggyServer;
  domain: string;
  endpoint: string;
  failedTool: string;
  toolContext: Record<string, string | number | boolean>;
  flowDescription: string;
}> = [
  {
    server: "food",
    domain: "food",
    endpoint: "POST mcp.swiggy.com/food",
    failedTool: "place_food_order",
    toolContext: {
      restaurantId: "rest_green_bowl",
      cartId: "food_cart_preview",
      menu_item_id: "paneer_bowl",
      paymentMethod: "COD",
    },
    flowDescription: "searched restaurant -> built food cart -> user confirmed -> place_food_order returned an upstream error",
  },
  {
    server: "instamart",
    domain: "im",
    endpoint: "POST mcp.swiggy.com/im",
    failedTool: "checkout",
    toolContext: {
      addressId: "addr_home_001",
      cartId: "im_cart_preview",
      spinId: "spin_moong_dal",
      paymentMethod: "COD",
    },
    flowDescription: "searched groceries -> updated cart -> refreshed cart -> checkout returned an upstream error",
  },
  {
    server: "dineout",
    domain: "dineout",
    endpoint: "POST mcp.swiggy.com/dineout",
    failedTool: "book_table",
    toolContext: {
      restaurantId: "la_piazza",
      cartId: "dineout_cart_preview",
      slotId: "sat_1945",
      guestCount: 4,
    },
    flowDescription: "searched Dineout -> selected slot -> created cart -> book_table returned an upstream error",
  },
];

function scoreFor(hasSession: boolean) {
  return hasSession ? 100 : 88;
}

function bodyFor(sessionId: string | undefined, reports: SupportBridgeToolReport[]) {
  return [
    "MealPilot Swiggy MCP support bridge report",
    "",
    `Session id: ${sessionId ?? "pending local session"}`,
    "Servers: food, instamart, dineout",
    "Issue: user-visible MCP failure during a confirmed MealPilot flow",
    "",
    "report_error payloads prepared:",
    ...reports.map((report) => `- ${report.server}.${report.failedTool}: ${report.responsePreview.data.supportCorrelation}`),
    "",
    "No access tokens, raw payment data, raw address text, or full order payloads are included.",
  ].join("\n");
}

function buildReportForServer(
  serverConfig: (typeof servers)[number],
  sessionId: string | undefined,
): SupportBridgeToolReport {
  const correlation = `${serverConfig.server}_${sessionId ?? "pending_session"}_${serverConfig.failedTool}`;
  const toolContext = {
    ...serverConfig.toolContext,
    mealPilotSessionId: sessionId ?? "pending_session",
    userConfirmedAction: true,
  };
  const args = {
    tool: serverConfig.failedTool,
    domain: serverConfig.domain,
    errorMessage: `MealPilot simulated ${serverConfig.failedTool} failure for Swiggy support bridge validation.`,
    flowDescription: serverConfig.flowDescription,
    toolContext,
    userNotes: "Generated by MealPilot Support Bridge after user-visible failure. Tokens and PII are redacted.",
  };
  const subject = `[S2] MealPilot ${serverConfig.server} ${serverConfig.failedTool} support bridge`;
  const body = [
    args.errorMessage,
    "",
    `Domain: ${args.domain}`,
    `Tool: ${args.tool}`,
    `Session: ${sessionId ?? "pending local session"}`,
    `Flow: ${args.flowDescription}`,
    `Context keys: ${Object.keys(args.toolContext).join(", ")}`,
  ].join("\n");

  return {
    id: `support_${serverConfig.server}`,
    server: serverConfig.server,
    endpoint: serverConfig.endpoint,
    failedTool: serverConfig.failedTool,
    status: sessionId ? "ready" : "needs_session",
    request: {
      jsonrpc: "2.0",
      id: `support-${serverConfig.server}`,
      method: "tools/call",
      params: {
        name: "report_error",
        arguments: args,
      },
    },
    responsePreview: {
      success: true,
      data: {
        mailto: `mailto:builders@swiggy.in?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,
        summary: `${serverConfig.server} support payload prepared for ${serverConfig.failedTool}.`,
        supportCorrelation: correlation,
      },
      message: "Preview mirrors Swiggy report_error success envelope.",
    },
    evidence:
      "Uses official report_error fields: tool, domain, errorMessage, flowDescription, toolContext, and userNotes.",
  };
}

export function buildSupportBridgeReport(options: { plans: MealPlan[]; sessionId?: string }): SupportBridgeReport {
  const selectedPlan =
    options.sessionId !== undefined ? options.plans.find((plan) => plan.id === options.sessionId) : options.plans.at(-1);
  const sessionId = selectedPlan?.id ?? options.sessionId;
  const reportErrorTools = servers.map((server) => buildReportForServer(server, sessionId));
  const body = bodyFor(sessionId, reportErrorTools);

  return {
    generatedAt: new Date().toISOString(),
    score: scoreFor(Boolean(sessionId)),
    latestSessionId: sessionId,
    reportErrorTools,
    contactChannels: [
      {
        channel: "builders@swiggy.in",
        useCase: "General developer questions, onboarding, rate-limit increases, docs feedback, and production escalation email.",
        status: "ready",
      },
      {
        channel: "security@swiggy.in",
        useCase: "Responsible disclosure for security vulnerabilities.",
        status: "external",
      },
      {
        channel: "report_error tool",
        useCase: "Agent-invoked user report during a live Food, Instamart, or Dineout session.",
        status: "ready",
      },
    ],
    slaMatrix: [
      { severity: "S0", trigger: "Production down for integration users", ack: "< 30 min", updateCadence: "Every 30 min" },
      { severity: "S1", trigger: "Major feature broken or partial outage", ack: "< 2 hr business hours", updateCadence: "Every 2 hr" },
      { severity: "S2", trigger: "Degraded quality or non-critical issue", ack: "< 1 business day", updateCadence: "Daily" },
      { severity: "S3", trigger: "Question or feature request", ack: "< 3 business days", updateCadence: "As needed" },
    ],
    redactionRules: [
      "Never include access tokens, refresh tokens, cookies, or OAuth authorization codes.",
      "Do not include raw payment credentials, full addresses, or complete order payloads.",
      "Include only the identifiers needed for Swiggy tracing: orderId, restaurantId, addressId, spinId, cartId, slotId, couponCode, query, paymentMethod, and MealPilot session id.",
      "Keep user notes short and remove phone numbers, emails, and free-form address text before sending.",
    ],
    escalationChecklist: [
      "Capture the MealPilot session id and UTC or IST time range.",
      "Call report_error once on the affected Swiggy server when the user asks to report from the conversation.",
      "Attach expected versus actual behavior and the specific failed tool name.",
      "Email builders@swiggy.in for production incidents after verifying tokens, scopes, endpoints, and error-rate spike.",
    ],
    incidentEmail: {
      to: "builders@swiggy.in",
      subject: `[S2] MealPilot Swiggy MCP support bridge${sessionId ? ` - ${sessionId}` : ""}`,
      body,
    },
    externalGates: [
      "Live report_error server-side logging requires an authenticated Swiggy MCP session.",
      "Enterprise S0/S1 phone or Slack escalation depends on the partner agreement.",
      "Public status page and partner dashboards are Swiggy-operated external systems.",
    ],
  };
}
