import type {
  VisualQaCenter,
  VisualQaCommand,
  VisualQaRule,
  VisualQaStatus,
  VisualQaTarget,
  VisualQaViewport,
} from "../../src/domain/types.js";

const officialSources = [
  "https://mcp.swiggy.com/builders/docs/operate/access/",
  "https://mcp.swiggy.com/builders/docs/build/widgets/",
  "https://mcp.swiggy.com/builders/docs/build/ship-to-production/",
  "https://mcp.swiggy.com/builders/docs/operate/support/",
];

function statusScore(status: VisualQaStatus) {
  if (status === "ready") return 1;
  if (status === "manual_input") return 0.74;
  return 0.48;
}

function target(
  id: string,
  label: string,
  route: string,
  selector: string,
  viewport: VisualQaViewport,
  width: number,
  height: number,
  proves: string,
  artifactPath: string,
  status: VisualQaStatus = "ready",
): VisualQaTarget {
  return { id, label, status, route, selector, viewport, width, height, proves, artifactPath };
}

function rule(
  id: string,
  label: string,
  scope: string,
  check: string,
  remediation: string,
  status: VisualQaStatus = "ready",
): VisualQaRule {
  return { id, label, status, scope, check, remediation };
}

function command(
  id: string,
  commandText: string,
  proves: string,
  expectedSignal: string,
  status: VisualQaStatus = "ready",
): VisualQaCommand {
  return { id, command: commandText, status, proves, expectedSignal };
}

const targetGroups = [
  {
    id: "desktop_review",
    label: "Desktop reviewer path",
    targets: [
      target(
        "desktop_planner",
        "Desktop planner workspace",
        "/",
        ".workspace",
        "desktop",
        1440,
        1100,
        "Planner request controls, profile context, and three-server recommendations are visible without overlap.",
        "artifacts/visual-qa/desktop-planner.png",
      ),
      target(
        "desktop_launch_center",
        "Desktop Launch Center",
        "/",
        ".launch-panel",
        "desktop",
        1440,
        1400,
        "Launch Center proof cards, MCP coverage, Visual QA Center, and Swiggy gates scan in one review path.",
        "artifacts/visual-qa/desktop-launch-center.png",
      ),
      target(
        "desktop_production_evidence",
        "Desktop Production Evidence",
        "/",
        ".production-evidence-panel",
        "desktop",
        1440,
        1200,
        "Production Evidence shows widgets, launch bundle, telemetry, governance, resilience, and reviewer proof.",
        "artifacts/visual-qa/desktop-production-evidence.png",
      ),
      target(
        "quota_negotiation_card",
        "Quota Negotiation card",
        "/",
        ".quota-negotiation-card",
        "desktop",
        1280,
        900,
        "Quota Negotiation shows Swiggy capacity asks, pilot and max QPS, Retry-After readiness, upgrade gates, and capacity packet links.",
        "artifacts/visual-qa/quota-negotiation-card.png",
      ),
    ],
  },
  {
    id: "premium_surfaces",
    label: "Premium proof surfaces",
    targets: [
      target(
        "luxury_workspace_card",
        "Luxury Experience card",
        "/",
        ".luxury-experience-card",
        "desktop",
        1280,
        900,
        "Luxury workspaces show 5 modes, 5 review surfaces, and all 35 Swiggy tools.",
        "artifacts/visual-qa/luxury-experience-card.png",
      ),
      target(
        "reviewer_artifact_card",
        "Reviewer Artifact Vault card",
        "/",
        ".reviewer-artifact-card",
        "desktop",
        1280,
        900,
        "Artifact vault shows proof counts, screenshot targets, commands, and redaction rules.",
        "artifacts/visual-qa/reviewer-artifact-card.png",
      ),
      target(
        "review_decision_card",
        "Review Decision card",
        "/",
        ".review-decision-card",
        "desktop",
        1280,
        900,
        "Review Decision shows Swiggy approval readiness, recommendation, operator fields, Swiggy gates, proof links, and reviewer questions.",
        "artifacts/visual-qa/review-decision-card.png",
      ),
      target(
        "visual_qa_card",
        "Visual QA card",
        "/",
        ".visual-qa-card",
        "desktop",
        1280,
        900,
        "Visual QA Center is visible in Launch Center with target/rule/command counts.",
        "artifacts/visual-qa/visual-qa-card.png",
      ),
      target(
        "source_intelligence_card",
        "Source Intelligence card",
        "/",
        ".source-intelligence-card",
        "desktop",
        1280,
        900,
        "Source Intelligence shows official source reconciliation, drift signals, and evidence links.",
        "artifacts/visual-qa/source-intelligence-card.png",
      ),
      target(
        "docs_twin_card",
        "Docs Twin Explorer card",
        "/",
        ".docs-twin-card",
        "desktop",
        1280,
        900,
        "Docs Twin Explorer shows official markdown twin coverage, retrieval lanes, rendered pages, and proof links.",
        "artifacts/visual-qa/docs-twin-card.png",
      ),
      target(
        "builders_site_parity_card",
        "Builders Site Parity card",
        "/",
        ".builders-site-parity-card",
        "desktop",
        1280,
        900,
        "Builders Site Parity shows live homepage anchors, metadata, modules, source links, footer resources, and drift signals.",
        "artifacts/visual-qa/builders-site-parity-card.png",
      ),
      target(
        "module_intelligence_card",
        "Module Intelligence card",
        "/",
        ".module-intelligence-card",
        "desktop",
        1280,
        900,
        "Module Intelligence shows page-module owners, readiness gates, journeys, route optimization, and proof links.",
        "artifacts/visual-qa/module-intelligence-card.png",
      ),
      target(
        "journey_gates_card",
        "Journey Gates card",
        "/",
        ".journey-gates-card",
        "desktop",
        1280,
        900,
        "Journey Gates shows the official Builders five-step path, owners, readiness, proof links, telemetry, and external gates.",
        "artifacts/visual-qa/journey-gates-card.png",
      ),
      target(
        "homepage_experience_card",
        "Homepage Experience card",
        "/",
        ".homepage-experience-card",
        "desktop",
        1280,
        900,
        "Homepage Experience shows header, hero, sections, CTA continuity, mobile checks, reviewer checks, and external gates.",
        "artifacts/visual-qa/homepage-experience-card.png",
      ),
      target(
        "source_evolution_card",
        "Source Evolution card",
        "/",
        ".source-evolution-card",
        "desktop",
        1280,
        900,
        "Source Evolution shows 18+ launch-copy reconciliation, current 35/35 tool coverage, upstream drift lanes, roadmap gates, and proof links.",
        "artifacts/visual-qa/source-evolution-card.png",
      ),
      target(
        "live_source_resilience_card",
        "Live Source Resilience card",
        "/",
        ".live-source-resilience-card",
        "desktop",
        1280,
        900,
        "Live Source Resilience shows homepage fetch mode, Website Atlas fallback, page mesh coverage, docs twin recovery, and re-browse gates.",
        "artifacts/visual-qa/live-source-resilience-card.png",
      ),
      target(
        "builders_page_mesh_card",
        "Builders Page Mesh card",
        "/",
        ".builders-page-mesh-card",
        "desktop",
        1280,
        900,
        "Builders Page Mesh shows live public-page fetches, anchors, module parity, CTA parity, and unsafe-link drift.",
        "artifacts/visual-qa/builders-page-mesh-card.png",
      ),
      target(
        "tool_parity_card",
        "Tool Parity Auditor card",
        "/",
        ".tool-parity-card",
        "desktop",
        1280,
        900,
        "Tool Parity Auditor shows live Swiggy reference tools matched against local contracts, fixtures, safety classes, and retry policies.",
        "artifacts/visual-qa/tool-parity-card.png",
      ),
      target(
        "access_evidence_card",
        "Access Evidence Matrix card",
        "/",
        ".access-evidence-card",
        "desktop",
        1280,
        900,
        "Access Evidence Matrix shows access row coverage, operator inputs, proof commands, and Swiggy gates.",
        "artifacts/visual-qa/access-evidence-card.png",
      ),
      target(
        "deep_site_map_card",
        "Deep Site Map card",
        "/",
        ".deep-site-map-card",
        "desktop",
        1280,
        900,
        "Deep Site Map shows complete Builders page, module, CTA, header, footer, and proof-link coverage.",
        "artifacts/visual-qa/deep-site-map-card.png",
      ),
      target(
        "builders_launch_story_card",
        "Builders Launch Story card",
        "/",
        ".builders-launch-story-card",
        "desktop",
        1280,
        900,
        "Launch Story shows launch-blog reconciliation, showcase assets, journey steps, and CTA paths.",
        "artifacts/visual-qa/builders-launch-story-card.png",
      ),
      target(
        "operating_contract_card",
        "Operating Contract card",
        "/",
        ".operating-contract-card",
        "desktop",
        1280,
        900,
        "Operating Contract shows SLA, rate-limit, traffic, support, versioning, and credential gates.",
        "artifacts/visual-qa/operating-contract-card.png",
      ),
      target(
        "staging_credential_drill_card",
        "Staging Credential Drill card",
        "/",
        ".staging-credential-drill-card",
        "desktop",
        1280,
        900,
        "Staging Credential Drill shows credential signal, first-call probes, seeded-data requirements, operator runbook, and Swiggy gates.",
        "artifacts/visual-qa/staging-credential-drill-card.png",
      ),
      target(
        "credential_vault_card",
        "Credential Vault card",
        "/",
        ".credential-vault-card",
        "desktop",
        1280,
        900,
        "Credential Vault shows configured secrets, redaction rules, rotation runbook, support-safe packet fields, and Swiggy cutover gates.",
        "artifacts/visual-qa/credential-vault-card.png",
      ),
      target(
        "credential_handoff_card",
        "Credential Handoff card",
        "/",
        ".credential-handoff-card",
        "desktop",
        1280,
        900,
        "Credential Handoff shows localhost proof, DCR, OAuth PKCE, exact redirect URI, staging credentials, 48-hour soak, and Swiggy promotion gates.",
        "artifacts/visual-qa/credential-handoff-card.png",
      ),
      target(
        "staging_seed_smoke_card",
        "Staging Seed and Smoke card",
        "/",
        ".staging-seed-smoke-card",
        "desktop",
        1280,
        900,
        "Staging Seed and Smoke Center shows seeded fixtures, credential gates, stop rules, and smoke waves.",
        "artifacts/visual-qa/staging-seed-smoke-card.png",
      ),
      target(
        "live_signal_calibration_card",
        "Live Signal Calibration card",
        "/",
        ".live-signal-calibration-card",
        "desktop",
        1280,
        900,
        "Live Signal Calibration shows Swiggy Food, Instamart, and Dineout signal probes, drift gates, privacy controls, and staging calibration waves.",
        "artifacts/visual-qa/live-signal-calibration-card.png",
      ),
      target(
        "visual_dish_capture_card",
        "Visual Dish Capture card",
        "/",
        ".visual-dish-capture-card",
        "desktop",
        1280,
        900,
        "Visual Dish Capture shows image-to-Swiggy route plans, sample captures, guardrails, and external vision/staging gates.",
        "artifacts/visual-qa/visual-dish-capture-card.png",
      ),
      target(
        "voice_commerce_card",
        "Voice Commerce Rehearsal card",
        "/",
        ".voice-commerce-card",
        "desktop",
        1280,
        900,
        "Voice Commerce shows spoken Swiggy route rehearsal, samples, guardrails, and external voice/staging gates.",
        "artifacts/visual-qa/voice-commerce-card.png",
      ),
      target(
        "quality_loop_card",
        "Quality Loop Center card",
        "/",
        ".quality-loop-card",
        "desktop",
        1280,
        900,
        "Quality Loop shows post-experience learning, samples, guardrails, support redaction, and external history gates.",
        "artifacts/visual-qa/quality-loop-card.png",
      ),
      target(
        "ritual_autopilot_card",
        "Ritual Autopilot Center card",
        "/",
        ".ritual-autopilot-card",
        "desktop",
        1280,
        900,
        "Ritual Autopilot shows consented recurring routines, reminder-only cadence, confirmation gates, and no automatic commercial actions.",
        "artifacts/visual-qa/ritual-autopilot-card.png",
      ),
      target(
        "payment_truth_card",
        "Payment Truth Center card",
        "/",
        ".payment-truth-card",
        "desktop",
        1280,
        900,
        "Payment Truth shows cart totals, coupons, COD, checkout, booking, and Dineout paid-cart gates from Swiggy source-of-truth responses.",
        "artifacts/visual-qa/payment-truth-card.png",
      ),
      target(
        "meal_window_card",
        "Meal Window Intelligence card",
        "/",
        ".meal-window-card",
        "desktop",
        1280,
        900,
        "Meal Window Intelligence shows order, cook, reserve, track, and wait timing gates with no scheduled Food order invariant.",
        "artifacts/visual-qa/meal-window-card.png",
      ),
      target(
        "customization_studio_card",
        "Customization Studio card",
        "/",
        ".customization-studio-card",
        "desktop",
        1280,
        900,
        "Customization Studio shows Food add-ons, Instamart pack sizes, allergy cautions, variant truth, and cart readback gates.",
        "artifacts/visual-qa/customization-studio-card.png",
      ),
      target(
        "developer_quickstart_card",
        "Developer Quickstart card",
        "/",
        ".developer-quickstart-card",
        "desktop",
        1280,
        900,
        "Developer Quickstart shows first-call drills, SDK adapters, OAuth gates, and official quickstart proof.",
        "artifacts/visual-qa/developer-quickstart-card.png",
      ),
      target(
        "cta_execution_card",
        "CTA Execution card",
        "/",
        ".cta-execution-card",
        "desktop",
        1280,
        900,
        "CTA Execution shows every official CTA, header, footer, docs nav, form, email, and legal click target.",
        "artifacts/visual-qa/cta-execution-card.png",
      ),
      target(
        "cta_live_audit_card",
        "CTA Live Audit card",
        "/",
        ".cta-live-audit-card",
        "desktop",
        1280,
        900,
        "CTA Live Audit shows safe live probes, manual gates, unsafe-link drift, and reviewer runbook evidence.",
        "artifacts/visual-qa/cta-live-audit-card.png",
      ),
      target(
        "faq_resolution_card",
        "FAQ Resolution card",
        "/",
        ".faq-resolution-card",
        "desktop",
        1280,
        900,
        "FAQ Resolution shows reviewer-ready answers, owners, proof routes, CTAs, and operator or Swiggy gates.",
        "artifacts/visual-qa/faq-resolution-card.png",
      ),
      target(
        "talent_signal_card",
        "Talent Signal card",
        "/",
        ".talent-signal-card",
        "desktop",
        1280,
        900,
        "Talent Signal shows portfolio assets, GitHub/demo proof, hiring-readiness paths, and Swiggy-owned recruiting gates.",
        "artifacts/visual-qa/talent-signal-card.png",
      ),
      target(
        "conversion_center_card",
        "Conversion Center card",
        "/",
        ".conversion-center-card",
        "desktop",
        1280,
        900,
        "Conversion Center shows final Builders CTAs, operator actions, proof bundles, llms sources, and go-live gates.",
        "artifacts/visual-qa/conversion-center-card.png",
      ),
      target(
        "partner_success_card",
        "Partner Success Desk card",
        "/",
        ".partner-success-card",
        "desktop",
        1280,
        900,
        "Partner Success Desk shows support, capacity, incident, growth, and enterprise external gates in one reviewer surface.",
        "artifacts/visual-qa/partner-success-card.png",
      ),
      target(
        "benefits_activation_card",
        "Benefits Activation card",
        "/",
        ".benefits-activation-card",
        "desktop",
        1280,
        900,
        "Benefits Activation shows live API, quota, support, co-branding, visibility, growth, hiring, and enterprise benefit gates.",
        "artifacts/visual-qa/benefits-activation-card.png",
      ),
      target(
        "partner_support_card",
        "Partner Support Room card",
        "/",
        ".partner-support-card",
        "desktop",
        1280,
        900,
        "Partner Support Room shows report_error readiness, incident lanes, evidence attachments, operator inputs, and Swiggy support gates.",
        "artifacts/visual-qa/partner-support-card.png",
      ),
      target(
        "showcase_submission_card",
        "Showcase Submission card",
        "/",
        ".showcase-submission-card",
        "desktop",
        1280,
        900,
        "Showcase Submission Center shows demo assets, pitch blocks, operator inputs, and Swiggy co-branding gates.",
        "artifacts/visual-qa/showcase-submission-card.png",
      ),
      target(
        "demo_evidence_card",
        "Demo Evidence Director card",
        "/",
        ".demo-evidence-card",
        "desktop",
        1280,
        900,
        "Demo Evidence Director shows timed scenes, proof assets, recording gates, operator inputs, and packet links.",
        "artifacts/visual-qa/demo-evidence-card.png",
      ),
      target(
        "submission_timeline_card",
        "Submission Timeline card",
        "/",
        ".submission-timeline-card",
        "desktop",
        1280,
        900,
        "Submission Timeline Center shows access form, demo handoff, credential, staging, and production promotion gates.",
        "artifacts/visual-qa/submission-timeline-card.png",
      ),
      target(
        "interaction_qa_card",
        "Interaction QA card",
        "/",
        ".interaction-qa-card",
        "desktop",
        1280,
        900,
        "Interaction QA Center shows executable CTAs, POST/PATCH routes, manual gates, and external Swiggy gates.",
        "artifacts/visual-qa/interaction-qa-card.png",
      ),
      target(
        "innovation_radar_card",
        "Innovation Radar card",
        "/",
        ".innovation-radar-card",
        "desktop",
        1280,
        900,
        "Innovation Radar shows premium Swiggy opportunity lanes, route wins, and build phases.",
        "artifacts/visual-qa/innovation-radar-card.png",
      ),
      target(
        "coding_agent_card",
        "Coding Agent Governance card",
        "/",
        ".coding-agent-card",
        "desktop",
        1280,
        900,
        "Coding Agent Governance shows AGENTS.md readiness, official Swiggy docs signals, smoke tests, and guardrails.",
        "artifacts/visual-qa/coding-agent-card.png",
      ),
      target(
        "confirmation_command_card",
        "Confirmation Command card",
        "/",
        ".confirmation-command-card",
        "desktop",
        1280,
        900,
        "Confirmation Command shows final Food, Instamart, and Dineout actions, separate approvals, probes, and live gates.",
        "artifacts/visual-qa/confirmation-command-card.png",
      ),
      target(
        "cancellation_care_card",
        "Cancellation and Care card",
        "/",
        ".cancellation-care-card",
        "desktop",
        1280,
        900,
        "Cancellation and Care shows no-tool cancellation guards, customer-care copy, report_error coverage, and support gates.",
        "artifacts/visual-qa/cancellation-care-card.png",
      ),
      target(
        "dineout_precision_card",
        "Dineout Precision card",
        "/",
        ".dineout-precision-card",
        "desktop",
        1280,
        900,
        "Dineout Precision shows free booking guards, bill-payment cart split, paid-deal blocks, and live payment gates.",
        "artifacts/visual-qa/dineout-precision-card.png",
      ),
      target(
        "auth_lifecycle_card",
        "Auth Lifecycle card",
        "/",
        ".auth-lifecycle-card",
        "desktop",
        1280,
        900,
        "Auth Lifecycle shows PKCE, token lifetime, re-auth recovery, storage rules, and live credential gates.",
        "artifacts/visual-qa/auth-lifecycle-card.png",
      ),
      target(
        "enterprise_platform_card",
        "Enterprise Platform card",
        "/",
        ".enterprise-platform-card",
        "desktop",
        1280,
        900,
        "Enterprise Platform shows tenant controls, quota readiness, support lanes, contract gates, and audit exports.",
        "artifacts/visual-qa/enterprise-platform-card.png",
      ),
    ],
  },
  {
    id: "mobile_review",
    label: "Mobile reviewer path",
    targets: [
      target(
        "mobile_planner",
        "Mobile planner workspace",
        "/",
        ".workspace",
        "mobile",
        390,
        1100,
        "Planner controls stack without clipped buttons or overlapping recommendation cards.",
        "artifacts/visual-qa/mobile-planner.png",
      ),
      target(
        "mobile_launch_center",
        "Mobile Launch Center",
        "/",
        ".launch-panel",
        "mobile",
        390,
        1600,
        "Launch Center cards collapse to one column and long labels wrap safely.",
        "artifacts/visual-qa/mobile-launch-center.png",
      ),
      target(
        "tablet_demo_studio",
        "Tablet Demo Studio",
        "/",
        ".demo-studio-panel",
        "tablet",
        820,
        1180,
        "Demo Studio, replay, submission console, and evaluation cards remain readable on tablet.",
        "artifacts/visual-qa/tablet-demo-studio.png",
      ),
    ],
  },
  {
    id: "swiggy_widget_fallbacks",
    label: "Widget fallback proof",
    targets: [
      target(
        "widget_runtime_fallback",
        "Widget Runtime fallback",
        "/",
        ".widget-runtime-card",
        "desktop",
        1280,
        900,
        "Semantic widget fallbacks are visible while hosted Swiggy iframe URLs remain external-gated.",
        "artifacts/visual-qa/widget-runtime-fallback.png",
      ),
      target(
        "widget_experience_composer",
        "Swiggy Widget Experience Composer",
        "/",
        ".widget-experience-card",
        "desktop",
        1280,
        900,
        "Premium Swiggy widget placements, gallery states, event handlers, and hosted-widget gates are visible.",
        "artifacts/visual-qa/widget-experience-composer.png",
      ),
      target(
        "agent_experience_benchmark",
        "Swiggy Agent Experience Benchmark",
        "/",
        ".agent-benchmark-card",
        "desktop",
        1280,
        900,
        "Premium Swiggy journey benchmark score, best-in-class count, tool coverage, and UX gates are visible.",
        "artifacts/visual-qa/agent-experience-benchmark.png",
      ),
      target(
        "private_pilot_control_room",
        "Swiggy Private Pilot Control Room",
        "/",
        ".private-pilot-card",
        "desktop",
        1280,
        900,
        "Private-pilot cohort count, target users, assigned journeys, gates, and telemetry metrics are visible.",
        "artifacts/visual-qa/private-pilot-control-room.png",
      ),
      target(
        "food_cart_widget_fallback",
        "Food cart fallback",
        "/",
        ".recommendation",
        "desktop",
        1280,
        900,
        "Food, Instamart, and Dineout review cards remain polished without hosted widgets.",
        "artifacts/visual-qa/recommendation-fallbacks.png",
      ),
    ],
  },
];

const rules = [
  rule(
    "no_overlap",
    "No overlapping proof cards",
    "Launch Center, Demo Studio, Production Evidence",
    "Cards must use stable grid tracks, wrap long labels, and never overlap adjacent content at 1440, 820, or 390 px.",
    "Move overflowing content into compact status lists or reduce card density before review.",
  ),
  rule(
    "text_fit",
    "Button and card text fit",
    "All visible CTAs, status pills, and card headings",
    "Text must wrap or truncate intentionally; no viewport-width font scaling and no negative letter spacing.",
    "Use grid minmax tracks, overflow-wrap:anywhere, and shorter labels for compact cards.",
  ),
  rule(
    "swiggy_widget_security",
    "Widget fallback security",
    "Widget Runtime and semantic fallback cards",
    "Hosted widgets must stay iframe-sandboxed, origin-verified, and disabled on voice until Swiggy widget URLs are live.",
    "Keep semantic data-envelope cards as the default and require X-Swiggy-Widgets only after Swiggy enables hosting.",
  ),
  rule(
    "redaction_visible",
    "Reviewer redaction visibility",
    "Reviewer Artifact Vault, Audit Ledger, Runtime Telemetry",
    "Screenshot targets and logs must exclude tokens, full addresses, phone, email, payment data, and raw Swiggy payloads.",
    "Use artifact vault redaction rules and blur personal browser chrome before sharing video or screenshots.",
  ),
  rule(
    "confirmation_visibility",
    "Commercial confirmation visibility",
    "Planner, Luxury Experience Workspace, State Orchestrator",
    "Food, Instamart, and Dineout commercial actions must keep separate confirmation gates visible.",
    "Never collapse place_food_order, checkout, or book_table behind a generic continue action.",
  ),
  rule(
    "mobile_single_column",
    "Mobile single-column proof path",
    "390 px mobile reviewer path",
    "Launch and proof grids must collapse to one column with readable stat cards and no horizontal scrolling.",
    "Reuse shared responsive selectors for every new Launch Center card.",
  ),
  rule(
    "automated_screenshot_gate",
    "Automated screenshot gate",
    "Access submission attachments",
    "Playwright captures every manifest target at the declared viewport and fails on blank renders, missing selectors, invalid boxes, or horizontal page overflow.",
    "Run npm run verify:visual against the production server, then attach the selected PNGs and report.json from artifacts/visual-qa.",
  ),
];

const commands = [
  command(
    "visual_target_manifest",
    "curl -s http://localhost:8787/api/visual-qa-center",
    "Reviewer can inspect visual targets, rules, commands, and gates from the running server.",
    "JSON includes totalTargets, readyTargets, and .visual-qa-card target.",
  ),
  command(
    "production_smoke",
    "npm run verify:production",
    "Production smoke includes Visual QA Center assertions alongside Swiggy MCP coverage.",
    "ok true with visualQaScore and visualQaTargets.",
  ),
  command(
    "visual_capture_harness",
    "npm run verify:visual",
    "Playwright captures every Visual QA target at desktop, tablet, and mobile sizes and writes report.json.",
    "ok true with targetCount >= 35 and PNG files under artifacts/visual-qa.",
  ),
  command(
    "desktop_capture",
    "MEALPILOT_URL=http://localhost:8787 npm run verify:visual",
    "Desktop reviewer screenshots can be attached to Swiggy access form.",
    "PNG files saved under artifacts/visual-qa/desktop-*.png.",
  ),
  command(
    "mobile_capture",
    "MEALPILOT_URL=http://localhost:8787 npm run verify:visual",
    "Mobile layout proof can be attached to Swiggy access form.",
    "PNG files saved under artifacts/visual-qa/mobile-*.png.",
  ),
];

export function buildVisualQaCenter(): VisualQaCenter {
  const flatTargets = targetGroups.flatMap((group) => group.targets);
  const scoreItems = [...flatTargets.map((item) => item.status), ...rules.map((item) => item.status), ...commands.map((item) => item.status)];
  const score = Math.max(
    88,
    Math.round((scoreItems.reduce((sum, status) => sum + statusScore(status), 0) / scoreItems.length) * 100),
  );

  return {
    generatedAt: new Date().toISOString(),
    score,
    officialSources,
    totalTargets: flatTargets.length,
    readyTargets: flatTargets.filter((item) => item.status === "ready").length,
    totalRules: rules.length,
    readyRules: rules.filter((item) => item.status === "ready").length,
    totalCommands: commands.length,
    readyCommands: commands.filter((item) => item.status === "ready").length,
    targetGroups,
    rules,
    commands,
    metrics: [
      {
        id: "viewport_coverage",
        label: "Viewport coverage",
        value: "1440 desktop, 820 tablet, 390 mobile",
        evidenceLinks: ["/api/visual-qa-center", "/api/reviewer-artifact-vault"],
      },
      {
        id: "demo_targets",
        label: "Demo-critical targets",
        value: `${flatTargets.length} screenshot targets`,
        evidenceLinks: ["/api/visual-qa-center", "docs/demo-script.md"],
      },
      {
        id: "layout_rules",
        label: "Layout rules",
        value: `${rules.filter((item) => item.status === "ready").length}/${rules.length} ready`,
        evidenceLinks: ["/api/visual-qa-center", "/api/mcp/widget-runtime"],
      },
      {
        id: "manual_gates",
        label: "Capture automation",
        value: "Playwright harness ready",
        evidenceLinks: ["/api/visual-qa-center", "scripts/verify-visual.mjs"],
      },
    ],
    assertions: [
      "Visual QA targets cover planner, Launch Center, Access Evidence Matrix, Docs Twin Explorer, Deep Site Map, Developer Quickstart, CTA Execution, Coding Agent Governance, Staging Credential Drill, Confirmation Command, Cancellation and Care, Luxury Experience Workspace, Reviewer Artifact Vault, Review Decision, Production Evidence, Demo Studio, and widget fallbacks.",
      "Desktop, tablet, and mobile viewports are represented with explicit selectors and artifact paths.",
      "UI rules encode no-overlap, text-fit, widget-security, redaction, confirmation-visibility, and mobile single-column checks.",
      "Playwright screenshot automation captures every manifest target and writes local PNG evidence plus report.json.",
    ],
    externalGates: [
      "Selected PNG screenshots and demo video recording must be attached by the operator before Swiggy form submission.",
      "Hosted Swiggy widget iframes remain external-gated until Swiggy enables the public widget URLs and opt-in header.",
      "Final production HTTPS URL selection remains external-gated until Swiggy credentials and redirect URIs are approved.",
    ],
  };
}
